In [1]:
# Welcome to your new notebook
# Type here in the cell editor to add code!
print("nse_data_exploration")

StatementMeta(, efcba2ff-cc32-4573-a3e2-6af1034b068d, 3, Finished, Available, Finished, False)

fabric notebook

In [2]:
import pandas as pd

data = {
    "stock": ["TCS", "INFY", "RELIANCE"],
    "price": [3500, 1800, 2900]
}

df = pd.DataFrame(data)

df

StatementMeta(, efcba2ff-cc32-4573-a3e2-6af1034b068d, 4, Finished, Available, Finished, False)

      stock  price
0       TCS   3500
1      INFY   1800
2  RELIANCE   2900

## **Cleaning NSE Security**

In [9]:
import pandas as pd
df_nse = pd.read_csv("/lakehouse/default/Files/data/raw/nse/nse_security.csv")

df_nse.head()

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5,1,INE144J01027,5
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10,1,INE253B01015,10
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1,1,INE466L01038,1
3,3BBLACKBIO,3B Blackbio Dx Limited,EQ,20-APR-2026,10,1,INE994E01018,10
4,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10,1,INE748C01038,10

In [4]:
df_nse.columns

Index(['SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING',
       ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE'],
      dtype='object')

In [10]:
df_nse.columns = df_nse.columns.str.strip()
df_nse.columns

Index(['SYMBOL', 'NAME OF COMPANY', 'SERIES', 'DATE OF LISTING',
       'PAID UP VALUE', 'MARKET LOT', 'ISIN NUMBER', 'FACE VALUE'],
      dtype='object')

In [6]:
df_nse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2365 entries, 0 to 2364
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SYMBOL           2365 non-null   object
 1   NAME OF COMPANY  2365 non-null   object
 2   SERIES           2365 non-null   object
 3   DATE OF LISTING  2365 non-null   object
 4   PAID UP VALUE    2365 non-null   int64
 5   MARKET LOT       2365 non-null   int64
 6   ISIN NUMBER      2365 non-null   object
 7   FACE VALUE       2365 non-null   int64
dtypes: int64(3), object(5)
memory usage: 147.9+ KB

In [11]:
df_nse['DATE OF LISTING'] = pd.to_datetime(df_nse['DATE OF LISTING'])
df_nse.info()

/tmp/ipykernel_312/1346262559.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_nse['DATE OF LISTING'] = pd.to_datetime(df_nse['DATE OF LISTING'])

In [11]:
df_nse.describe()

                     DATE OF LISTING  PAID UP VALUE   MARKET LOT   FACE VALUE
count                           2365    2365.000000  2365.000000  2365.000000
mean   2013-10-23 17:51:37.674418432       6.452008     1.125159     6.452008
min              1995-02-08 00:00:00       1.000000     1.000000     1.000000
25%              2006-01-04 00:00:00       2.000000     1.000000     2.000000
50%              2016-03-30 00:00:00       5.000000     1.000000     5.000000
75%              2023-02-09 00:00:00      10.000000     1.000000    10.000000
max              2026-06-01 00:00:00    1000.000000   100.000000  1000.000000
std                              NaN      20.836218     3.210531    20.836218

## **Cleaning BSE security**

In [4]:
import pandas as pd


columns = [
    "Security Code",
    "Issuer Name",
    "Security Id",
    "Security Name",
    "Status",
    "Group",
    "Face Value",
    "ISIN No",
    "Instrument"
]

df_bse = pd.read_csv(
    "/lakehouse/default/Files/data/raw/bse/bse_security.csv",
    usecols=range(9),
    names=columns,
    header=0
)

df_bse.head()

,Security Code,Issuer Name,Security Id,Security Name,Status,Group,Face Value,ISIN No,Instrument
0,500002,ABB India Limited,ABB,ABB India Ltd,Active,A,2.0,INE117A01022,Equity
1,500003,Aegis Logistics Ltd.,AEGISLOG,Aegis Logistics Ltd,Active,A,1.0,INE208C01025,Equity
2,500008,Amara Raja Energy & Mobility Limited,ARE&M,Amara Raja Energy & Mobility Ltd,Active,A,1.0,INE885A01032,Equity
3,500009,Ambalal Sarabhai Enterprise Ltd.,AMBALALSA,Ambalal Sarabhai Enterprises Ltd,Active,B,10.0,INE432A01017,Equity
4,500012,Andhra Petrochemicals Ltd.,ANDHRAPET,Andhra Petrochemicals Ltd,Active,X,10.0,INE714B01016,Equity

In [5]:
type(df_bse)

pandas.core.frame.DataFrame

In [6]:
with open("/lakehouse/default/Files/data/raw/bse/bse_security.csv", "r", encoding="utf-8",errors="ignore") as f:
    for i in range(5):
        print(f.readline())

Security Code,Issuer Name,Security Id,Security Name,Status,Group,Face Value,ISIN No,Instrument

500002,ABB India Limited,ABB,ABB India Ltd,Active,A ,2.00,INE117A01022,Equity,,,,,

500003,Aegis Logistics Ltd.,AEGISLOG,Aegis Logistics Ltd,Active,A ,1.00,INE208C01025,Equity,,,,,

500008,Amara Raja Energy & Mobility Limited,ARE&M,Amara Raja Energy & Mobility Ltd,Active,A ,1.00,INE885A01032,Equity,,,,,

500009,Ambalal Sarabhai Enterprise Ltd.,AMBALALSA,Ambalal Sarabhai Enterprises Ltd,Active,B ,10.00,INE432A01017,Equity,,,,,

In [7]:
df_bse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4856 entries, 0 to 4855
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Security Code  4856 non-null   int64
 1   Issuer Name    4856 non-null   object
 2   Security Id    4856 non-null   object
 3   Security Name  4856 non-null   object
 4   Status         4856 non-null   object
 5   Group          4856 non-null   object
 6   Face Value     4856 non-null   float64
 7   ISIN No        4856 non-null   object
 8   Instrument     4856 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 341.6+ KB

## **Merging to get security master**

In [13]:
print("nse columns")
print(df_nse.columns)

print("\n bse columns")
print(df_bse.columns)

nse columns
Index(['SYMBOL', 'NAME OF COMPANY', 'SERIES', 'DATE OF LISTING',
       'PAID UP VALUE', 'MARKET LOT', 'ISIN NUMBER', 'FACE VALUE'],
      dtype='object')

 bse columns
Index(['Security Code', 'Issuer Name', 'Security Id', 'Security Name',
       'Status', 'Group', 'Face Value', 'ISIN No', 'Instrument'],
      dtype='object')

In [14]:
print("nse shape",df_nse.shape)
print("bse shape",df_bse.shape)

nse shape (2365, 8)
bse shape (4856, 9)

In [17]:
print("nse sample \n",df_nse[['SYMBOL','NAME OF COMPANY','ISIN NUMBER']].head())
print("\n bse sample \n",df_bse[['Security Name','Issuer Name','ISIN No']].head())

nse sample
        SYMBOL                           NAME OF COMPANY   ISIN NUMBER
0   20MICRONS                        20 Microns Limited  INE144J01027
1  21STCENMGM  21st Century Management Services Limited  INE253B01015
2      360ONE                       360 ONE WAM LIMITED  INE466L01038
3  3BBLACKBIO                    3B Blackbio Dx Limited  INE994E01018
4   3IINFOLTD                       3i Infotech Limited  INE748C01038

 bse sample
                       Security Name                           Issuer Name  \
0                     ABB India Ltd                     ABB India Limited
1               Aegis Logistics Ltd                  Aegis Logistics Ltd.
2  Amara Raja Energy & Mobility Ltd  Amara Raja Energy & Mobility Limited
3  Ambalal Sarabhai Enterprises Ltd      Ambalal Sarabhai Enterprise Ltd.
4         Andhra Petrochemicals Ltd            Andhra Petrochemicals Ltd.

        ISIN No
0  INE117A01022
1  INE208C01025
2  INE885A01032
3  INE432A01017
4  INE714B01016

In [19]:
common_isin = set(df_nse['ISIN NUMBER']).intersection(set(df_bse['ISIN No']))

print(len(common_isin))

2234

In [20]:
sec_master_preview = pd.merge(df_nse, df_bse, left_on='ISIN NUMBER', right_on='ISIN No', how = 'inner')
sec_master_preview.head()

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,Security Code,Issuer Name,Security Id,Security Name,Status,Group,Face Value,ISIN No,Instrument
0,20MICRONS,20 Microns Limited,EQ,2008-10-06,5,1,INE144J01027,5,533022,20 Microns Limited,20MICRONS,20 Microns Ltd,Active,B,5.0,INE144J01027,Equity
1,21STCENMGM,21st Century Management Services Limited,EQ,1995-05-03,10,1,INE253B01015,10,526921,Twentyfirst Century Management Serv,21STCENMGM,Twentyfirst Century Management Services Ltd,Active,B,10.0,INE253B01015,Equity
2,360ONE,360 ONE WAM LIMITED,EQ,2019-09-19,1,1,INE466L01038,1,542772,360 ONE WAM LIMITED,360ONE,360 ONE WAM LTD,Active,A,1.0,INE466L01038,Equity
3,3BBLACKBIO,3B Blackbio Dx Limited,EQ,2026-04-20,10,1,INE994E01018,10,532067,3B BlackBio Dx Limited,3BBLACKBIO,3B BlackBio Dx Ltd,Active,B,10.0,INE994E01018,Equity
4,3IINFOLTD,3i Infotech Limited,EQ,2021-10-22,10,1,INE748C01038,10,532628,3i Infotech limited,3IINFOLTD,3i Infotech Ltd,Active,B,10.0,INE748C01038,Equity

In [21]:
sec_master_preview.shape

(2234, 17)

In [22]:
print("duplicate nse",df_nse['ISIN NUMBER'].duplicated().sum())
print("duplicate bse",df_bse['ISIN No'].duplicated().sum())

duplicate nse 0
duplicate bse 0

In [23]:
sec_master = sec_master_preview[[
    'SYMBOL',
    'NAME OF COMPANY',
    'Security Code',
    'SERIES',
    'DATE OF LISTING',
    'MARKET LOT',
    'FACE VALUE',
    'ISIN NUMBER',
    'Status',
    'Group',
    'Instrument'
]]

sec_master.columns = [
    'symbol',
    'company_name',
    'bse_security_code',
    'series',
    'listing_date',
    'market_lot',
    'face_value',
    'isin',
    'status',
    'group',
    'instrument'
]

sec_master.head()

,symbol,company_name,bse_security_code,series,listing_date,market_lot,face_value,isin,status,group,instrument
0,20MICRONS,20 Microns Limited,533022,EQ,2008-10-06,1,5,INE144J01027,Active,B,Equity
1,21STCENMGM,21st Century Management Services Limited,526921,EQ,1995-05-03,1,10,INE253B01015,Active,B,Equity
2,360ONE,360 ONE WAM LIMITED,542772,EQ,2019-09-19,1,1,INE466L01038,Active,A,Equity
3,3BBLACKBIO,3B Blackbio Dx Limited,532067,EQ,2026-04-20,1,10,INE994E01018,Active,B,Equity
4,3IINFOLTD,3i Infotech Limited,532628,EQ,2021-10-22,1,10,INE748C01038,Active,B,Equity

In [24]:
sec_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2234 entries, 0 to 2233
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symbol             2234 non-null   object
 1   company_name       2234 non-null   object
 2   bse_security_code  2234 non-null   int64
 3   series             2234 non-null   object
 4   listing_date       2234 non-null   datetime64[ns]
 5   market_lot         2234 non-null   int64
 6   face_value         2234 non-null   int64
 7   isin               2234 non-null   object
 8   status             2234 non-null   object
 9   group              2234 non-null   object
 10  instrument         2234 non-null   object
dtypes: datetime64[ns](1), int64(3), object(7)
memory usage: 192.1+ KB

In [25]:
sec_master.to_csv("/lakehouse/default/Files/data/processed/sec_master.csv", index=False)
print("security master created")

security master created

## **Cleaning historic data**

In [4]:
import pandas as pd
df_nse_trade = pd.read_csv("/lakehouse/default/Files/data/raw/nse_history/3IINFOLTD.csv")

df_nse_trade.tail()

,Symbol,Date,Close,High,Low,Open,Volume
5156,3IINFOLTD,2026-03-12,13.140000343322754,13.350000381469727,13.100000381469727,13.300000190734863,606858
5157,3IINFOLTD,2026-03-13,12.8100004196167,13.369999885559082,12.710000038146973,13.369999885559082,550899
5158,3IINFOLTD,2026-03-16,12.859999656677246,13.050000190734863,12.680000305175781,12.90999984741211,447673
5159,3IINFOLTD,2026-03-17,12.720000267028809,13.039999961853027,12.699999809265137,13.0,687976
5160,3IINFOLTD,2026-03-18,13.529999732971191,13.699999809265137,12.850000381469727,12.920000076293945,981618

In [5]:
df_nse_trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5161 entries, 0 to 5160
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Symbol  5160 non-null   object
 1   Date    5160 non-null   object
 2   Close   5161 non-null   object
 3   High    5161 non-null   object
 4   Low     5161 non-null   object
 5   Open    5161 non-null   object
 6   Volume  5161 non-null   object
dtypes: object(7)
memory usage: 282.4+ KB

## **Creating folder structure**

In [5]:
folders = [
    "/lakehouse/default/Files/data/raw/nse_sec",
    "/lakehouse/default/Files/data/raw/bse_sec",
    "/lakehouse/default/Files/data/raw/nse_sec_inc",
    "/lakehouse/default/Files/data/raw/bse_sec_inc",

    "/lakehouse/default/Files/data/raw/nse_trade_hist",
    "/lakehouse/default/Files/data/raw/bse_trade_hist",
    "/lakehouse/default/Files/data/raw/nse_trade_inc",
    "/lakehouse/default/Files/data/raw/bse_trade_inc",

    "/lakehouse/default/Files/data/raw/nse_bulk_hist",
    "/lakehouse/default/Files/data/raw/nse_block_hist",
    "/lakehouse/default/Files/data/raw/bse_bulk_hist",
    "/lakehouse/default/Files/data/raw/bse_block_hist",

    "/lakehouse/default/Files/data/raw/nse_bulk_inc",
    "/lakehouse/default/Files/data/raw/nse_block_inc",
    "/lakehouse/default/Files/data/raw/bse_bulk_inc",
    "/lakehouse/default/Files/data/raw/bse_block_inc",

    "/lakehouse/default/Files/data/raw/nse_mcap",
    "/lakehouse/default/Files/data/raw/bse_mcap",

    "/lakehouse/default/Files/data/raw/sec_ind",

    "/lakehouse/default/Files/data/processed",
    "/lakehouse/default/Files/data/curated"
]

import os

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders created")

Folders created

In [7]:
import shutil

shutil.move(
    "/lakehouse/default/Files/data/raw/nse/nse_security.csv",
    "/lakehouse/default/Files/data/raw/nse_sec/nse_security.csv"
)

shutil.move(
    "/lakehouse/default/Files/data/raw/bse/bse_security.csv",
    "/lakehouse/default/Files/data/raw/bse_sec/bse_security.csv"
)

print("Files moved successfully!")

Files moved successfully!

## **NSE Trade Historical**

In [5]:
import pandas as pd
import yfinance as yf
import os
from datetime import date


# Read NSE security file
df_sec = pd.read_csv(
    "/lakehouse/default/Files/data/raw/nse_sec/nse_security.csv"
)

# Get all unique NSE symbols
symbols = (
    df_sec["SYMBOL"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

START_DATE = "2001-01-01"
END_DATE = date.today().isoformat()

SAVE_DIR = "/lakehouse/default/Files/data/raw/nse_trade_hist"


for symbol in symbols:
    try:
        ticker = f"{symbol}.NS"

        print(f"Downloading {ticker}")

        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            interval="1d",
            progress=False
        )

        # Fix extra yfinance ticker header
        df.columns = df.columns.get_level_values(0)

        if df.empty:
            print(f"{symbol}: no data")
            continue

        df = df.reset_index()
        df.insert(0, "Symbol", symbol)

        file_path = os.path.join(
            SAVE_DIR,
            f"{symbol}.csv"
        )

        df.to_csv(file_path, index=False)

        print(f"{symbol}: saved")

    except Exception as e:
        print(f"{symbol}: ERROR -> {e}")

print("NSE historical download completed")

Downloading 20MICRONS.NS
20MICRONS: saved
Downloading 21STCENMGM.NS
21STCENMGM: saved
Downloading 360ONE.NS
360ONE: saved
Downloading 3BBLACKBIO.NS
3BBLACKBIO: saved
Downloading 3IINFOLTD.NS
3IINFOLTD: saved
Downloading 3MINDIA.NS
3MINDIA: saved
Downloading 3PLAND.NS
3PLAND: saved
Downloading 5PAISA.NS
5PAISA: saved
Downloading 63MOONS.NS
63MOONS: saved
Downloading A2ZINFRA.NS
A2ZINFRA: saved
Downloading AAATECH.NS
AAATECH: saved
Downloading AADHARHFC.NS
AADHARHFC: saved
Downloading AAKASH.NS
AAKASH: saved
Downloading AAREYDRUGS.NS
AAREYDRUGS: saved
Downloading AARNAV.NS
AARNAV: saved
Downloading AARON.NS
AARON: saved
Downloading AARTECH.NS
AARTECH: saved
Downloading AARTIDRUGS.NS
AARTIDRUGS: saved
Downloading AARTIIND.NS
AARTIIND: saved
Downloading AARTIPHARM.NS
AARTIPHARM: saved
Downloading AARTISURF.NS
AARTISURF: saved
Downloading AARVI.NS
AARVI: saved
Downloading AAVAS.NS
AAVAS: saved
Downloading ABANSENT.NS
ABANSENT: saved
Downloading ABB.NS
ABB: saved
Downloading ABBOTINDIA.NS
ABBOTINDIA: saved
Downloading ABCAPITAL.NS
ABCAPITAL: saved
Downloading ABCOTS.NS
ABCOTS: saved
Downloading ABDL.NS
ABDL: saved
Downloading ABFRL.NS
ABFRL: saved
Downloading ABINFRA.NS
ABINFRA: saved
Downloading ABLBL.NS
ABLBL: saved
Downloading ABMINTLLTD.NS
ABMINTLLTD: saved
Downloading ABMKNO.NS
ABMKNO: saved
Downloading ABREL.NS
ABREL: saved
Downloading ABSLAMC.NS
ABSLAMC: saved
Downloading ACC.NS
ACC: saved
Downloading ACCELYA.NS
ACCELYA: saved
Downloading ACCURACY.NS
ACCURACY: saved
Downloading ACE.NS
ACE: saved
Downloading ACEINTEG.NS
ACEINTEG: saved
Downloading ACI.NS
ACI: saved
Downloading ACL.NS
ACL: saved
Downloading ACMESOLAR.NS
ACMESOLAR: saved
Downloading ACSTECH.NS
ACSTECH: saved
Downloading ACUTAAS.NS
ACUTAAS: saved
Downloading ADANIENSOL.NS
ADANIENSOL: saved
Downloading ADANIENT.NS
ADANIENT: saved
Downloading ADANIGREEN.NS
ADANIGREEN: saved
Downloading ADANIPORTS.NS
ADANIPORTS: saved
Downloading ADANIPOWER.NS
ADANIPOWER: saved
Downloading ADFFOODS.NS
ADFFOODS: saved
Downloading ADL.NS
ADL: saved
Downloading ADOR.NS
ADOR: saved
Downloading ADROITINFO.NS
ADROITINFO: saved
Downloading ADSL.NS
ADSL: saved
Downloading ADVAIT.NS
ADVAIT: saved
Downloading ADVANCE.NS
ADVANCE: saved
Downloading ADVANIHOTR.NS
ADVANIHOTR: saved
Downloading ADVENTHTL.NS
ADVENTHTL: saved
Downloading ADVENZYMES.NS
ADVENZYMES: saved
Downloading AEGISLOG.NS
AEGISLOG: saved
Downloading AEGISVOPAK.NS
AEGISVOPAK: saved
Downloading AEPL.NS
AEPL: saved
Downloading AEQUS.NS
AEQUS: saved
Downloading AEROENTER.NS
AEROENTER: saved
Downloading AEROFLEX.NS
AEROFLEX: saved
Downloading AERONEU.NS
AERONEU: saved
Downloading AETHER.NS
AETHER: saved
Downloading AFCONS.NS
AFCONS: saved
Downloading AFFLE.NS
AFFLE: saved
Downloading AFFORDABLE.NS
AFFORDABLE: saved
Downloading AFIL.NS
AFIL: saved
Downloading AFSL.NS
AFSL: saved
Downloading AGARIND.NS
AGARIND: saved
Downloading AGARWALEYE.NS
AGARWALEYE: saved
Downloading AGI.NS
AGI: saved
Downloading AGIIL.NS
AGIIL: saved
Downloading AGRITECH.NS
AGRITECH: saved
Downloading AGROPHOS.NS
AGROPHOS: saved
Downloading AHCL.NS
AHCL: saved
Downloading AHLADA.NS
AHLADA: saved
Downloading AHLEAST.NS
AHLEAST: saved
Downloading AHLUCONT.NS
AHLUCONT: saved
Downloading AHLWEST.NS
AHLWEST: saved
Downloading AIAENG.NS
AIAENG: saved
Downloading AIIL.NS
AIIL: saved
Downloading AIRAN.NS
AIRAN: saved
Downloading AIROLAM.NS
AIROLAM: saved
Downloading AJANTPHARM.NS
AJANTPHARM: saved
Downloading AJAXENGG.NS
AJAXENGG: saved
Downloading AJMERA.NS
AJMERA: saved
Downloading AJOONI.NS
AJOONI: saved
Downloading AKASH.NS
AKASH: saved
Downloading AKCAPIT.NS
AKCAPIT: saved
Downloading AKG.NS
AKG: saved
Downloading AKI.NS
AKI: saved
Downloading AKSHAR.NS
AKSHAR: saved
Downloading AKSHARCHEM.NS
AKSHARCHEM: saved
Downloading AKSHOPTFBR.NS
AKSHOPTFBR: saved
Downloading AKUMS.NS
AKUMS: saved
Downloading ALANKIT.NS
ALANKIT: saved
Downloading ALBERTDAVD.NS
ALBERTDAVD: saved
Downloading ALEMBICLTD.NS
ALEMBICLTD: saved
Downloading ALGOQUANT.NS
ALGOQUANT: saved
Downloading ALICON.NS
ALICON: saved
Downloading ALIVUS.NS
ALIVUS: saved
Downloading ALKALI.NS
ALKALI: saved
Downloading ALKEM.NS
ALKEM: saved
Downloading ALKYLAMINE.NS
ALKYLAMINE: saved
Downloading ALLCARGO.NS
ALLCARGO: saved
Downloading ALLDIGI.NS
ALLDIGI: saved
Downloading ALLTIME.NS
ALLTIME: saved
Downloading ALMONDZ.NS
ALMONDZ: saved
Downloading ALOKINDS.NS
ALOKINDS: saved
Downloading ALPA.NS
ALPA: saved
Downloading ALPHAGEO.NS
ALPHAGEO: saved
Downloading AMAGI.NS
AMAGI: saved
Downloading AMANTA.NS
AMANTA: saved
Downloading AMBALALSA.NS
AMBALALSA: saved
Downloading AMBER.NS
AMBER: saved
Downloading AMBICAAGAR.NS
AMBICAAGAR: saved
Downloading AMBIKCO.NS
AMBIKCO: saved
Downloading AMBUJACEM.NS
AMBUJACEM: saved
Downloading AMDIND.NS
AMDIND: saved
Downloading AMIRCHAND.NS
AMIRCHAND: saved
Downloading AMJLAND.NS
AMJLAND: saved
Downloading AMNPLST.NS
AMNPLST: saved
Downloading AMRUTANJAN.NS
AMRUTANJAN: saved
Downloading ANANDRATHI.NS
ANANDRATHI: saved
Downloading ANANTRAJ.NS
ANANTRAJ: saved
Downloading ANDHRAPAP.NS
ANDHRAPAP: saved
Downloading ANDHRSUGAR.NS
ANDHRSUGAR: saved
Downloading ANGELONE.NS
ANGELONE: saved
Downloading ANIKINDS.NS
ANIKINDS: saved
Downloading ANKITMETAL.NS
ANKITMETAL: saved
Downloading ANMOL.NS
ANMOL: saved
Downloading ANSALAPI.NS
ANSALAPI: saved
Downloading ANTELOPUS.NS
ANTELOPUS: saved
Downloading ANTGRAPHIC.NS
ANTGRAPHIC: saved
Downloading ANTHEM.NS
ANTHEM: saved
Downloading ANUHPHR.NS
ANUHPHR: saved
Downloading ANUP.NS
ANUP: saved
Downloading ANURAS.NS
ANURAS: saved
Downloading APARINDS.NS
APARINDS: saved
Downloading APCL.NS
APCL: saved
Downloading APCOTEXIND.NS
APCOTEXIND: saved
Downloading APEX.NS
APEX: saved
Downloading APLAPOLLO.NS
APLAPOLLO: saved
Downloading APLLTD.NS
APLLTD: saved
Downloading APOLLO.NS
APOLLO: saved
Downloading APOLLOHOSP.NS
APOLLOHOSP: saved
Downloading APOLLOPIPE.NS
APOLLOPIPE: saved
Downloading APOLLOTYRE.NS
APOLLOTYRE: saved
Downloading APOLSINHOT.NS
APOLSINHOT: saved
Downloading APTECHT.NS
APTECHT: saved
Downloading APTUS.NS
APTUS: saved
Downloading AQYLON.NS
AQYLON: saved
Downloading ARCHIDPLY.NS
ARCHIDPLY: saved
Downloading ARCHIES.NS
ARCHIES: saved
Downloading ARE&M.NS
ARE&M: saved
Downloading ARENTERP.NS
ARENTERP: saved
Downloading ARFIN.NS
ARFIN: saved
Downloading ARIES.NS
ARIES: saved
Downloading ARIHANT.NS
ARIHANT: saved
Downloading ARIHANTCAP.NS
ARIHANTCAP: saved
Downloading ARIHANTSUP.NS
ARIHANTSUP: saved
Downloading ARIS.NS
ARIS: saved
Downloading ARKADE.NS
ARKADE: saved
Downloading ARMANFIN.NS
ARMANFIN: saved
Downloading AROGRANITE.NS
AROGRANITE: saved
Downloading ARROWGREEN.NS
ARROWGREEN: saved
Downloading ARSHIYA.NS
ARSHIYA: saved
Downloading ARSSBL.NS
ARSSBL: saved
Downloading ARTEMISMED.NS
ARTEMISMED: saved
Downloading ARTNIRMAN.NS
ARTNIRMAN: saved
Downloading ARVEE.NS
ARVEE: saved
Downloading ARVIND.NS
ARVIND: saved
Downloading ARVINDFASN.NS
AVG-RE: no data
Downloading AVL.NS
AVL: saved
Downloading AVONMORE.NS
AVONMORE: saved
Downloading AVROIND.NS
AVROIND: saved
Downloading AVTNPL.NS
AVTNPL: saved
Downloading AWFIS.NS
AWFIS: saved
Downloading AWHCL.NS
AWHCL: saved
Downloading AWL.NS
AWL: saved
Downloading AXISBANK.NS
AXISBANK: saved
Downloading AXISCADES.NS
AXISCADES: saved
Downloading AXITA.NS
AXITA: saved
Downloading AYE.NS
AYE: saved
Downloading AYMSYNTEX.NS
AYMSYNTEX: saved
Downloading AZAD.NS
AZAD: saved
Downloading BAFNAPH.NS
BAFNAPH: saved
Downloading BAGFILMS.NS
BAGFILMS: saved
Downloading BAIDFIN.NS
BAIDFIN: saved
Downloading BAJAJ-AUTO.NS
BAJAJ-AUTO: saved
Downloading BAJAJCON.NS
BAJAJCON: saved
Downloading BAJAJELEC.NS
BAJAJELEC: saved
Downloading BAJAJFINSV.NS
BAJAJFINSV: saved
Downloading BAJAJHCARE.NS
BAJAJHCARE: saved
Downloading BAJAJHFL.NS
BAJAJHFL: saved
Downloading BAJAJHIND.NS
BAJAJHIND: saved
Downloading BAJAJHLDNG.NS
BAJAJHLDNG: saved
Downloading BAJAJINDEF.NS
BAJAJINDEF: saved
Downloading BAJAJST.NS
BAJAJST: saved
Downloading BAJEL.NS
BAJEL: saved
Downloading BAJFINANCE.NS
BAJFINANCE: saved
Downloading BALAJEE.NS
BALAJEE: saved
Downloading BALAJITELE.NS
BALAJITELE: saved
Downloading BALAMINES.NS
BALAMINES: saved
Downloading BALAXI.NS
BALAXI: saved
Downloading BALKRISHNA.NS
BALKRISHNA: saved
Downloading BALKRISIND.NS
BALKRISIND: saved
Downloading BALMLAWRIE.NS
BALMLAWRIE: saved
Downloading BALPHARMA.NS
BALPHARMA: saved
Downloading BALRAMCHIN.NS
BALRAMCHIN: saved
Downloading BALUFORGE.NS
BALUFORGE: saved
Downloading BANARBEADS.NS
BANARBEADS: saved
Downloading BANARISUG.NS
BANARISUG: saved
Downloading BANCOINDIA.NS
BANCOINDIA: saved
Downloading BANDHANBNK.NS
BANDHANBNK: saved
Downloading BANG.NS
BANG: saved
Downloading BANKA.NS
BANKA: saved
Downloading BANKBARODA.NS
BANKBARODA: saved
Downloading BANKINDIA.NS
BANKINDIA: saved
Downloading BANSALWIRE.NS
BANSALWIRE: saved
Downloading BANSWRAS.NS
BANSWRAS: saved
Downloading BASF.NS
BASF: saved
Downloading BASML.NS
BASML: saved
Downloading BATAINDIA.NS
BATAINDIA: saved
Downloading BATLIBOI.NS
BATLIBOI: saved
Downloading BAYERCROP.NS
BAYERCROP: saved
Downloading BBL.NS
BBL: saved
Downloading BBOX.NS
BBOX: saved
Downloading BBTC.NS
BBTC: saved
Downloading BBTCL.NS
BBTCL: saved
Downloading BCG.NS
BCG: saved
Downloading BCLIND.NS
BCLIND: saved
Downloading BCONCEPTS.NS
BCONCEPTS: saved
Downloading BCPL.NS
BCPL: saved
Downloading BDL.NS
BDL: saved
Downloading BEARDSELL.NS
BEARDSELL: saved
Downloading BECTORFOOD.NS
BECTORFOOD: saved
Downloading BEDMUTHA.NS
BEDMUTHA: saved
Downloading BEEKAY.NS
BEEKAY: saved
Downloading BEL.NS
BEL: saved
Downloading BELLACASA.NS
BELLACASA: saved
Downloading BELRISE.NS
BELRISE: saved
Downloading BEML.NS
BEML: saved
Downloading BENGALASM.NS
BENGALASM: saved
Downloading BEPL.NS
BEPL: saved
Downloading BERGEPAINT.NS
BERGEPAINT: saved
Downloading BESTAGRO.NS
BESTAGRO: saved
Downloading BETA.NS
BETA: saved
Downloading BFINVEST.NS
BFINVEST: saved
Downloading BFUTILITIE.NS
BFUTILITIE: saved
Downloading BGRENERGY.NS
BGRENERGY: saved
Downloading BHAGCHEM.NS
BHAGCHEM: saved
Downloading BHAGERIA.NS
BHAGERIA: saved
Downloading BHAGYANGR.NS
BHAGYANGR: saved
Downloading BHANDARI.NS
BHANDARI: saved
Downloading BHARATCOAL.NS
BHARATCOAL: saved
Downloading BHARATFORG.NS
BHARATFORG: saved
Downloading BHARATGEAR.NS
BHARATGEAR: saved
Downloading BHARATRAS.NS
BHARATRAS: saved
Downloading BHARATSE.NS
BHARATSE: saved
Downloading BHARATWIRE.NS
BHARATWIRE: saved
Downloading BHARTIARTL.NS
BHARTIARTL: saved
Downloading BHARTIHEXA.NS
BHARTIHEXA: saved
Downloading BHEL.NS
BHEL: saved
Downloading BI.NS
BI: saved
Downloading BIGBLOC.NS
BIGBLOC: saved
Downloading BIKAJI.NS
BIKAJI: saved
Downloading BIL.NS
BIL: saved
Downloading BIMETAL.NS
BIMETAL: saved
Downloading BIOCON.NS
BIOCON: saved
Downloading BIOFILCHEM.NS
BIOFILCHEM: saved
Downloading BIRLACABLE.NS
BIRLACABLE: saved
Downloading BIRLACORPN.NS
BIRLACORPN: saved
Downloading BIRLAMONEY.NS
BIRLAMONEY: saved
Downloading BIRLANU.NS
BIRLANU: saved
Downloading BIRLAPREC.NS
BIRLAPREC: saved
Downloading BLACKBUCK.NS
BLACKBUCK: saved
Downloading BLACKROSE.NS
BLACKROSE: saved
Downloading BLAL.NS
BLAL: saved
Downloading BLBLIMITED.NS
BLBLIMITED: saved
Downloading BLIL.NS
BLIL: saved
Downloading BLISSGVS.NS
BLISSGVS: saved
Downloading BLKASHYAP.NS
BLKASHYAP: saved
Downloading BLS.NS
BLS: saved
Downloading BLSE.NS
BLSE: saved
Downloading BLUECHIP.NS
BLUECHIP: saved
Downloading BLUECOAST.NS
BLUECOAST: saved
Downloading BLUEDART.NS
BLUEDART: saved
Downloading BLUEJET.NS
BLUEJET: saved
Downloading BLUESTARCO.NS
BLUESTARCO: saved
Downloading BLUESTONE.NS
BLUESTONE: saved
Downloading BLUSPRING.NS
BLUSPRING: saved
Downloading BMWVENTLTD.NS
BMWVENTLTD: saved
Downloading BNAGROCHEM.NS
BNAGROCHEM: saved
Downloading BNALTD.NS
BNALTD: saved
Downloading BODALCHEM.NS
BODALCHEM: saved
Downloading BOHRAIND.NS
BOHRAIND: saved
Downloading BOMDYEING.NS
BOMDYEING: saved
Downloading BONLON.NS
BONLON: saved
Downloading BORANA.NS
BORANA: saved
Downloading BOROLTD.NS
BOROLTD: saved
Downloading BORORENEW.NS
BORORENEW: saved
Downloading BOROSCI.NS
BOROSCI: saved
Downloading BOSCH-HCIL.NS
BOSCH-HCIL: saved
Downloading BOSCHLTD.NS
BOSCHLTD: saved
Downloading BPCL.NS
BPCL: saved
Downloading BPL.NS
BPL: saved
Downloading BRIGADE.NS
BRIGADE: saved
Downloading BRIGHOTEL.NS
BRIGHOTEL: saved
Downloading BRITANNIA.NS
BRITANNIA: saved
Downloading BRNL.NS
BRNL: saved
Downloading BROOKS.NS
BROOKS: saved
Downloading BSE.NS
BSE: saved
Downloading BSHSL.NS
BSHSL: saved
Downloading BSL.NS
BSL: saved
Downloading BSOFT.NS
BSOFT: saved
Downloading BTML.NS
BTML: saved
Downloading BTTL.NS
BTTL: saved
Downloading BUILDPRO.NS
BUILDPRO: saved
Downloading BUTTERFLY.NS
BUTTERFLY: saved
Downloading BVCL.NS
BVCL: saved
Downloading BYKE.NS
BYKE: saved
Downloading CALSOFT.NS
CALSOFT: saved
Downloading CAMLINFINE.NS
CAMLINFINE: saved
Downloading CAMPUS.NS
CAMPUS: saved
Downloading CAMS.NS
CAMS: saved
Downloading CANBK.NS
CANBK: saved
Downloading CANFINHOME.NS
CANFINHOME: saved
Downloading CANHLIFE.NS
CANHLIFE: saved
Downloading CANTABIL.NS
CANTABIL: saved
Downloading CAPACITE.NS
CAPACITE: saved
Downloading CAPILLARY.NS
CAPILLARY: saved
Downloading CAPITALSFB.NS
CAPITALSFB: saved
Downloading CAPLIPOINT.NS
CAPLIPOINT: saved
Downloading CAPTRUST.NS
CAPTRUST: saved
Downloading CARBORUNIV.NS
CARBORUNIV: saved
Downloading CARERATING.NS
CARERATING: saved
Downloading CARRARO.NS
CARRARO: saved
Downloading CARTRADE.NS
CARTRADE: saved
Downloading CARYSIL.NS
CARYSIL: saved
Downloading CASTROLIND.NS
CASTROLIND: saved
Downloading CCAVENUE.NS
CCAVENUE: saved
Downloading CCCL.NS
CCCL: saved
Downloading CCHHL.NS
CCHHL: saved
Downloading CCL.NS
CCL: saved
Downloading CDSL.NS
CDSL: saved
Downloading CEATLTD.NS
CEATLTD: saved
Downloading CEIGALL.NS
CEIGALL: saved
Downloading CEINSYS.NS
CEINSYS: saved
Downloading CELEBRITY.NS
CELEBRITY: saved
Downloading CELLO.NS
CELLO: saved
Downloading CEMPRO.NS
CEMPRO: saved
Downloading CENTENKA.NS
CENTENKA: saved
Downloading CENTEXT.NS
CENTEXT: saved
Downloading CENTRALBK.NS
CENTRALBK: saved
Downloading CENTRUM.NS
CENTRUM: saved
Downloading CENTUM.NS
CENTUM: saved
Downloading CENTURYPLY.NS
CENTURYPLY: saved
Downloading CERA.NS
CERA: saved
Downloading CEREBRAINT.NS
CEREBRAINT: saved
Downloading CESC.NS
CESC: saved
Downloading CEWATER.NS
CEWATER: saved
Downloading CGCL.NS
CGCL: saved
Downloading CGPOWER.NS
CGPOWER: saved
Downloading CHALET.NS
CHALET: saved
Downloading CHAMBLFERT.NS
CHAMBLFERT: saved
Downloading CHEMBOND.NS
CHEMBOND: saved
Downloading CHEMBONDCH.NS
CHEMBONDCH: saved
Downloading CHEMCON.NS
CHEMCON: saved
Downloading CHEMFAB.NS
CHEMFAB: saved
Downloading CHEMPLASTS.NS
CHEMPLASTS: saved
Downloading CHENNPETRO.NS
CHENNPETRO: saved
Downloading CHEVIOT.NS
CHEVIOT: saved
Downloading CHOICEIN.NS
CHOICEIN: saved
Downloading CHOLAFIN.NS
CHOLAFIN: saved
Downloading CHOLAHLDNG.NS
CHOLAHLDNG: saved
Downloading CIEINDIA.NS
CIEINDIA: saved
Downloading CIFL.NS
CIFL: saved
Downloading CINELINE.NS
CINELINE: saved
Downloading CINEVISTA.NS
CINEVISTA: saved
Downloading CIPLA.NS
CIPLA: saved
Downloading CLEAN.NS
CLEAN: saved
Downloading CLEANMAX.NS
CLEANMAX: saved
Downloading CLEDUCATE.NS
CLEDUCATE: saved
Downloading CLSEL.NS
CLSEL: saved
Downloading CMPDI.NS
CMPDI: saved
Downloading CMSINFO.NS
CMSINFO: saved
Downloading CNL.NS
CNL: saved
Downloading COALINDIA.NS
COALINDIA: saved
Downloading COASTCORP.NS
COASTCORP: saved
Downloading COCHINSHIP.NS
COCHINSHIP: saved
Downloading COCKERILL.NS
COCKERILL: saved
Downloading COFFEEDAY.NS
COFFEEDAY: saved
Downloading COFORGE.NS
COFORGE: saved
Downloading COHANCE.NS
COHANCE: saved
Downloading COLPAL.NS
COLPAL: saved
Downloading COMFINTE.NS
COMFINTE: saved
Downloading COMPINFO.NS
COMPINFO: saved
Downloading COMPUSOFT.NS
COMPUSOFT: saved
Downloading COMSYN.NS
COMSYN: saved
Downloading CONCOR.NS
CONCOR: saved
Downloading CONCORDBIO.NS
CONCORDBIO: saved
Downloading CONFIPET.NS
CONFIPET: saved
Downloading CONSOFINVT.NS
CONSOFINVT: saved
Downloading CONTROLPR.NS
CONTROLPR: saved
Downloading CORALFINAC.NS
CORALFINAC: saved
Downloading CORDSCABLE.NS
CORDSCABLE: saved
Downloading COROMANDEL.NS
COROMANDEL: saved
Downloading CORONA.NS
CORONA: saved
Downloading COSMOFIRST.NS
COSMOFIRST: saved
Downloading COUNCODOS.NS
COUNCODOS: saved
Downloading CPCAP.NS
CPCAP: saved
Downloading CPEDU.NS
CPEDU: saved
Downloading CPPLUS.NS
CPPLUS: saved
Downloading CRAFTSMAN.NS
CRAFTSMAN: saved
Downloading CRAMC.NS
CRAMC: saved
Downloading CREATIVEYE.NS
CREATIVEYE: saved
Downloading CREDITACC.NS
CREDITACC: saved
Downloading CREST.NS
CREST: saved
Downloading CRISIL.NS
CRISIL: saved
Downloading CRIZAC.NS
CRIZAC: saved
Downloading CROMPTON.NS
CROMPTON: saved
Downloading CROWN.NS
CROWN: saved
Downloading CSBBANK.NS
CSBBANK: saved
Downloading CSLFINANCE.NS
CSLFINANCE: saved
Downloading CTE.NS
CTE: saved
Downloading CUB.NS
CUB: saved
Downloading CUBEXTUB.NS
CUBEXTUB: saved
Downloading CUMMINSIND.NS
CUMMINSIND: saved
Downloading CUPID.NS
CUPID: saved
Downloading CURAA.NS
CURAA: saved
Downloading CYBERMEDIA.NS
CYBERMEDIA: saved
Downloading CYBERTECH.NS
CYBERTECH: saved
Downloading CYIENT.NS
CYIENT: saved
Downloading CYIENTDLM.NS
CYIENTDLM: saved
Downloading DABUR.NS
DABUR: saved
Downloading DAICHI.NS
DAICHI: saved
Downloading DALBHARAT.NS
DALBHARAT: saved
Downloading DALMIASUG.NS
DALMIASUG: saved
Downloading DAMCAPITAL.NS
DAMCAPITAL: saved
Downloading DAMODARIND.NS
DAMODARIND: saved
Downloading DANGEE.NS
DANGEE: saved
Downloading DATAMATICS.NS
DATAMATICS: saved
Downloading DATAPATTNS.NS
DATAPATTNS: saved
Downloading DAVANGERE.NS
DAVANGERE: saved
Downloading DBCORP.NS
DBCORP: saved
Downloading DBEIL.NS
DBEIL: saved
Downloading DBL.NS
DBL: saved
Downloading DBOL.NS
DBOL: saved
Downloading DBREALTY.NS
DBREALTY: saved
Downloading DBSTOCKBRO.NS
DBSTOCKBRO: saved
Downloading DCAL.NS
DCAL: saved
Downloading DCBBANK.NS
DCBBANK: saved
Downloading DCI.NS
DCI: saved
Downloading DCM.NS
DCM: saved
Downloading DCMFINSERV.NS
DCMFINSERV: saved
Downloading DCMNVL.NS
DCMNVL: saved
Downloading DCMSHRIRAM.NS
DCMSHRIRAM: saved
Downloading DCMSIL.NS
DCMSIL: saved
Downloading DCMSRIND.NS
DCMSRIND: saved
Downloading DCW.NS
DCW: saved
Downloading DCXINDIA.NS
DCXINDIA: saved
Downloading DDEVPLSTIK.NS
DDEVPLSTIK: saved
Downloading DECCANCE.NS
DECCANCE: saved
Downloading DECNGOLD.NS
DECNGOLD: saved
Downloading DEEDEV.NS
DEEDEV: saved
Downloading DEEPAKFERT.NS
DEEPAKFERT: saved
Downloading DEEPAKNTR.NS
DEEPAKNTR: saved
Downloading DEEPINDS.NS
DEEPINDS: saved
Downloading DELHIVERY.NS
DELHIVERY: saved
Downloading DELPHIFX.NS
DELPHIFX: saved
Downloading DELTACORP.NS
DELTACORP: saved
Downloading DELTAMAGNT.NS
DELTAMAGNT: saved
Downloading DEN.NS
DEN: saved
Downloading DENORA.NS
DENORA: saved
Downloading DENTA.NS
DENTA: saved
Downloading DEVIT.NS
DEVIT: saved
Downloading DEVX.NS
DEVX: saved
Downloading DEVYANI.NS
DEVYANI: saved
Downloading DGCONTENT.NS
DGCONTENT: saved
Downloading DHAMPURSUG.NS
DHAMPURSUG: saved
Downloading DHANBANK.NS
DHANBANK: saved
Downloading DHANUKA.NS
DHANUKA: saved
Downloading DHARMAJ.NS
DHARMAJ: saved
Downloading DHRUV.NS
DHRUV: saved
Downloading DHUNINV.NS
DHUNINV: saved
Downloading DIACABS.NS
DIACABS: saved
Downloading DIAMINESQ.NS
DIAMINESQ: saved
Downloading DIAMONDYD.NS
DIAMONDYD: saved
Downloading DICIND.NS
DICIND: saved
Downloading DIFFNKG.NS
DIFFNKG: saved
Downloading DIGIDRIVE.NS
DIGIDRIVE: saved
Downloading DIGISPICE.NS
DIGISPICE: saved
Downloading DIGITIDE.NS
DIGITIDE: saved
Downloading DIGJAMLMTD.NS
DIGJAMLMTD: saved
Downloading DISAQ.NS
DISAQ: saved
Downloading DISHTV.NS
DISHTV: saved
Downloading DIVGIITTS.NS
DIVGIITTS: saved
Downloading DIVISLAB.NS
DIVISLAB: saved
Downloading DIXON.NS
DIXON: saved
Downloading DJML.NS
DJML: saved
Downloading DLF.NS
DLF: saved
Downloading DLINKINDIA.NS
DLINKINDIA: saved
Downloading DMART.NS
DMART: saved
Downloading DMCC.NS
DMCC: saved
Downloading DNAMEDIA.NS
DNAMEDIA: saved
Downloading DODLA.NS
DODLA: saved
Downloading DOLATALGO.NS
DOLATALGO: saved
Downloading DOLLAR.NS
DOLLAR: saved
Downloading DOLPHIN.NS
DOLPHIN: saved
Downloading DOMS.NS
DOMS: saved
Downloading DONEAR.NS
DONEAR: saved
Downloading DPABHUSHAN.NS
DPABHUSHAN: saved

In [2]:
%pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (2025.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.0.6-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (18 kB)
Requirement already satisfied: protobuf>=3.19.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from yfinance) (5.29.3)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: soupsieve>1.2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2025.10.5)
Requirement already satisfied: rich in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (14.3.2)
Requirement already satisfied: pycparser in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: six>=1.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 115.6 MB/s  0:00:00
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.0.6-py3-none-any.whl (146 kB)
Downloading websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (184 kB)
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [yfinance]4/5 [yfinance]]]
Successfully installed curl_cffi-0.15.0 multitasking-0.0.13 peewee-4.0.6 websockets-16.0 yfinance-1.4.1
Note: you may need to restart the kernel to use updated packages.

## **BSE Trade Historical**

In [17]:
import pandas as pd
import yfinance as yf
import os
from datetime import date


# Read BSE security file correctly
columns = [
    "Security Code",
    "Issuer Name",
    "Security Id",
    "Security Name",
    "Status",
    "Group",
    "Face Value",
    "ISIN No",
    "Instrument"
]

df_sec = pd.read_csv(
    "/lakehouse/default/Files/data/raw/bse_sec/bse_security.csv",
    usecols=range(9),
    names=columns,
    header=0
)

# Get all unique BSE symbols
symbols = (
    df_sec["Security Id"]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

START_DATE = "2001-01-01"
END_DATE = date.today().isoformat()

SAVE_DIR = "/lakehouse/default/Files/data/raw/bse_trade_hist"


for symbol in symbols:
    try:
        ticker = f"{symbol}.BO"

        print(f"Downloading {ticker}")

        df = yf.download(
            ticker,
            start=START_DATE,
            end=END_DATE,
            interval="1d",
            progress=False
        )

        # Fix yfinance extra header
        df.columns = df.columns.get_level_values(0)

        if df.empty:
            print(f"{symbol}: no data")
            continue

        df = df.reset_index()
        df.insert(0, "Symbol", symbol)

        file_path = os.path.join(
            SAVE_DIR,
            f"{symbol}.csv"
        )

        df.to_csv(file_path, index=False)

        print(f"{symbol}: saved")

    except Exception as e:
        print(f"{symbol}: ERROR -> {e}")

print("BSE historical download completed")

Downloading ABB.BO
ABB: saved
Downloading AEGISLOG.BO
AEGISLOG: saved
Downloading ARE&M.BO
ARE&M: saved
Downloading AMBALALSA.BO
AMBALALSA: saved
Downloading ANDHRAPET.BO
ANDHRAPET: saved
Downloading ANSALAPI.BO
ANSALAPI: saved
Downloading UTIQUE.BO
UTIQUE: saved
Downloading ARUNAHTEL.BO
ARUNAHTEL: saved
Downloading BOMDYEING.BO
BOMDYEING: saved
Downloading ASIANHOTNR.BO
ASIANHOTNR: saved
Downloading ATUL.BO
ATUL: saved
Downloading ATVPR.BO
ATVPR: saved
Downloading BAJAJELEC.BO
BAJAJELEC: saved
Downloading BAJAJHIND.BO
BAJAJHIND: saved
Downloading FORCEMOT.BO
FORCEMOT: saved
Downloading BAJFINANCE.BO
BAJFINANCE: saved
Downloading BALRAMCHIN.BO
BALRAMCHIN: saved
Downloading BANCOINDIA.BO
BANCOINDIA: saved
Downloading ABREL.BO
ABREL: saved
Downloading BANARISUG.BO
BANARISUG: saved
Downloading BASF.BO
BASF: saved
Downloading BATAINDIA.BO
BATAINDIA: saved
Downloading BEML.BO
BEML: saved
Downloading BEL.BO
BEL: saved
Downloading BHAGGAS.BO
BHAGGAS: saved
Downloading BEPL.BO
BEPL: saved
Downloading BIHSPONG.BO
BIHSPONG: saved
Downloading BIRLACABLE.BO
BIRLACABLE: saved
Downloading BLUESTARCO.BO
BLUESTARCO: saved
Downloading DISAQ.BO
DISAQ: saved
Downloading QUESTCAP.BO
QUESTCAP: saved
Downloading BPL.BO
BPL: saved
Downloading OAL.BO
OAL: saved
Downloading CENTEXT.BO
CENTEXT: saved
Downloading CESC.BO
CESC: saved
Downloading CHAMBLFERT.BO
CHAMBLFERT: saved
Downloading EXIDEIND.BO
EXIDEIND: saved
Downloading CIPLA.BO
CIPLA: saved
Downloading DICIND.BO
DICIND: saved
Downloading CRISIL.BO
CRISIL: saved
Downloading CGPOWER.BO
CGPOWER: saved
Downloading DABUR.BO
DABUR: saved
Downloading DALMIASUG.BO
DALMIASUG: saved
Downloading ARVIND.BO
ARVIND: saved
Downloading BHEL.BO
BHEL: saved
Downloading HINDPETRO.BO
HINDPETRO: saved
Downloading IFCI.BO
IFCI: saved
Downloading MTNL.BO
MTNL: saved
Downloading MRPL.BO
MRPL: saved
Downloading CHENNPETRO.BO
CHENNPETRO: saved
Downloading SBIN.BO
SBIN: saved
Downloading SAIL.BO
SAIL: saved
Downloading TITAN.BO
TITAN: saved
Downloading IDBI.BO
IDBI: saved
Downloading DCW.BO
DCW: saved
Downloading DHAMPURSUG.BO
DHAMPURSUG: saved
Downloading DIAMINESQ.BO
DIAMINESQ: saved
Downloading ELANTAS.BO
ELANTAS: saved
Downloading DRREDDY.BO
DRREDDY: saved
Downloading EIDPARRY.BO
EIDPARRY: saved
Downloading PGHL.BO
PGHL: saved
Downloading ELECTCAST.BO
ELECTCAST: saved
Downloading ESABINDIA.BO
ESABINDIA: saved
Downloading EPL.BO
EPL: saved
Downloading ESTER.BO
ESTER: saved
Downloading FGP.BO
FGP: saved
Downloading PHCAP.BO
PHCAP: saved
Downloading FINCABLES.BO
FINCABLES: saved
Downloading COCKERILL.BO
COCKERILL: saved
Downloading UFLEX.BO
UFLEX: saved
Downloading FOSECOIND.BO
FOSECOIND: saved
Downloading GOLDENTOBC.BO
GOLDENTOBC: saved
Downloading GANESHBE.BO
GANESHBE: saved
Downloading METROGLOBL.BO
METROGLOBL: saved
Downloading GTL.BO
GTL: saved
Downloading GODFRYPHLP.BO
GODFRYPHLP: saved
Downloading GODREJIND.BO
GODREJIND: saved
Downloading KANSAINER.BO
KANSAINER: saved
Downloading GOODRICKE.BO
GOODRICKE: saved
Downloading GOODYEAR.BO
GOODYEAR: saved
Downloading GTNINDS.BO
GTNINDS: saved
Downloading GHCL.BO
GHCL: saved
Downloading GFLLIMITED.BO
GFLLIMITED: saved
Downloading GLFL.BO
GLFL: saved
Downloading HCL-INSYS.BO
HCL-INSYS: saved
Downloading HDFCBANK.BO
HDFCBANK: saved
Downloading HEROMOTOCO.BO
HEROMOTOCO: saved
Downloading HFCL.BO
HFCL: saved
Downloading HSCL.BO
HSCL: saved
Downloading HCC.BO
HCC: saved
Downloading HINDOILEXP.BO
HINDOILEXP: saved
Downloading AGI.BO
AGI: saved
Downloading HINDZINC.BO
HINDZINC: saved
Downloading NDLVENTURE.BO
NDLVENTURE: saved
Downloading HMT.BO
HMT: saved
Downloading PRAGBOS.BO
PRAGBOS: saved
Downloading HLVLTD.BO
HLVLTD: saved
Downloading IGPL.BO
IGPL: saved
Downloading INDIAGLYCO.BO
INDIAGLYCO: saved
Downloading INDLEASE.BO
INDLEASE: saved
Downloading MARGOFIN.BO
MARGOFIN: saved
Downloading INDORAMA.BO
INDORAMA: saved
Downloading INFY.BO
INFY: saved
Downloading INGERRAND.BO
INGERRAND: saved
Downloading ITHL.BO
ITHL: saved
Downloading IONEXCHANG.BO
IONEXCHANG: saved
Downloading SUNDROP.BO
SUNDROP: saved
Downloading JISLJALEQS.BO
JISLJALEQS: saved
Downloading JASCH.BO
JASCH: saved
Downloading JINDALPOLY.BO
JINDALPOLY: saved
Downloading JSWSTEEL.BO
JSWSTEEL: saved
Downloading KAJARIACER.BO
KAJARIACER: saved
Downloading KAKATCEM.BO
KAKATCEM: saved
Downloading KSL.BO
KSL: saved
Downloading WHIRLPOOL.BO
WHIRLPOOL: saved
Downloading KGDENIM.BO
KGDENIM: saved
Downloading KINETICENG.BO
KINETICENG: saved
Downloading KIRLOSBROS.BO
KIRLOSBROS: saved
Downloading KIRLOSIND.BO
KIRLOSIND: saved
Downloading KIRLFER.BO
KIRLFER: saved
Downloading ENVAIREL.BO
ENVAIREL: saved
Downloading KOTAKBANK.BO
KOTAKBANK: saved
Downloading KRIFILIND.BO
KRIFILIND: saved
Downloading KSB.BO
KSB: saved
Downloading LGBBROSLTD.BO
LGBBROSLTD: saved
Downloading TRENT.BO
TRENT: saved
Downloading LMW.BO
LMW: saved
Downloading LICHSGFIN.BO
LICHSGFIN: saved
Downloading LUPIN.BO
LUPIN: saved
Downloading LYKALABS.BO
LYKALABS: saved
Downloading RAMCOCEM.BO
RAMCOCEM: saved
Downloading HYBRIDFIN.BO
HYBRIDFIN: saved
Downloading MAFATIND.BO
MAFATIND: saved
Downloading MAHSEAMLES.BO
MAHSEAMLES: saved
Downloading MAHSCOOTER.BO
MAHSCOOTER: saved
Downloading MAJESAUT.BO
MAJESAUT: saved
Downloading MANALIPETC.BO
MANALIPETC: saved
Downloading BARODARY.BO
BARODARY: saved
Downloading MFSL.BO
MFSL: saved
Downloading MIDINDIA.BO
MIDINDIA: saved
Downloading MIRCELECTR.BO
MIRCELECTR: saved
Downloading CENTENKA.BO
CENTENKA: saved
Downloading MODTHREAD.BO
MODTHREAD: saved
Downloading LORDSCHLO.BO
LORDSCHLO: saved
Downloading SPICEJET.BO
SPICEJET: saved
Downloading MOREPENLAB.BO
MOREPENLAB: saved
Downloading MRF.BO
MRF: saved
Downloading HEIDELBERG.BO
HEIDELBERG: saved
Downloading NCC.BO
NCC: saved
Downloading VEDL.BO
VEDL: saved
Downloading NAHARSPING.BO
NAHARSPING: saved
Downloading NAPEROL.BO
NAPEROL: saved
Downloading GRASIM.BO
GRASIM: saved
Downloading NIITLTD.BO
NIITLTD: saved
Downloading JAYKAY.BO
JAYKAY: saved
Downloading NIRLON.BO
NIRLON: saved
Downloading ONGC.BO
ONGC: saved
Downloading OILCOUNTUB.BO
OILCOUNTUB: saved
Downloading ORIENTHOT.BO
ORIENTHOT: saved
Downloading OSWALAGRO.BO
OSWALAGRO: saved
Downloading INDSUCR.BO
INDSUCR: saved
Downloading PANCM.BO
PANCM: saved
Downloading RELIANCE.BO
RELIANCE: saved
Downloading PILITA.BO
PILITA: saved
Downloading RAYMOND.BO
RAYMOND: saved
Downloading PIDILITIND.BO
PIDILITIND: saved
Downloading PIXTRANS.BO
PIXTRANS: saved
Downloading BIRLACORPN.BO
BIRLACORPN: saved
Downloading SURYAROSNI.BO
SURYAROSNI: saved
Downloading PRIMESECU.BO
PRIMESECU: saved
Downloading PRSMJOHNSN.BO
PRSMJOHNSN: saved
Downloading RAIN.BO
RAIN: saved
Downloading PRUDMOULI.BO
PRUDMOULI: saved
Downloading AMJLAND.BO
AMJLAND: saved
Downloading PUNJCOMMU.BO
PUNJCOMMU: saved
Downloading RSWM.BO
RSWM: saved
Downloading RAJSREESUG.BO
RAJSREESUG: saved
Downloading RALLIS.BO
RALLIS: saved
Downloading RAMANEWS.BO
RAMANEWS: saved
Downloading RAMAPPR-B.BO
RAMAPPR-B: saved
Downloading RAPICUT.BO
RAPICUT: saved
Downloading WELSPLSOL.BO
WELSPLSOL: saved
Downloading RUBFILA.BO
RUBFILA: saved
Downloading PATANJALI.BO
PATANJALI: saved
Downloading SALORAINTL.BO
SALORAINTL: saved
Downloading SAMTELIN.BO
SAMTELIN: saved
Downloading JINDALSAW.BO
JINDALSAW: saved
Downloading JKLAKSHMI.BO
JKLAKSHMI: saved
Downloading SHREECEM.BO
SHREECEM: saved
Downloading SKPMIL.BO
SKPMIL: saved
Downloading SILVERLINE.BO
SILVERLINE: saved
Downloading TATAPOWER.BO
TATAPOWER: saved
Downloading SPMLINFRA.BO
SPMLINFRA: saved
Downloading SUNDRMFAST.BO
SUNDRMFAST: saved
Downloading SUNFLAG.BO
SUNFLAG: saved
Downloading SPLPETRO.BO
SPLPETRO: saved
Downloading SWARAJENG.BO
SWARAJENG: saved
Downloading TATAELXSI.BO
TATAELXSI: saved
Downloading ACC.BO
ACC: saved
Downloading THERMAX.BO
THERMAX: saved
Downloading TIRUMALCHM.BO
TIRUMALCHM: saved
Downloading THOMASCOOK.BO
THOMASCOOK: saved
Downloading TIMEX.BO
TIMEX: saved
Downloading TOKYOPLAST.BO
TOKYOPLAST: saved
Downloading TORNTPHARM.BO
TORNTPHARM: saved
Downloading TPINDIA.BO
TPINDIA: saved
Downloading TRANSCHEM.BO
TRANSCHEM: saved
Downloading AMBUJACEM.BO
AMBUJACEM: saved
Downloading UTLINDS.BO
UTLINDS: saved
Downloading UNIENTER.BO
UNIENTER: saved
Downloading VHL.BO
VHL: saved
Downloading HINDALCO.BO
HINDALCO: saved
Downloading WSTCSTPAPR.BO
WSTCSTPAPR: saved
Downloading HOCL.BO
HOCL: saved
Downloading MPILCORPL.BO
MPILCORPL: saved
Downloading PASUPTAC.BO
PASUPTAC: saved
Downloading TEAM24.BO
NIRBHAYIND: no data
Downloading DUROPACK.BO
DUROPACK: saved
Downloading SWARNSAR.BO
SWARNSAR: saved
Downloading GANESHHOU.BO
GANESHHOU: saved
Downloading NMDC.BO
NMDC: saved
Downloading CINDHO.BO
CINDHO: saved
Downloading PATINTLOG.BO
PATINTLOG: saved
Downloading ALPHAGEO.BO
ALPHAGEO: saved
Downloading HAMPTON.BO
HAMPTON: saved
Downloading KKALPANAIND.BO
KKALPANAIND: saved
Downloading OKPLA.BO
OKPLA: saved
Downloading KRITI.BO
KRITI: saved
Downloading WELTI.BO
WELTI: saved
Downloading ASMTEC.BO
ASMTEC: saved
Downloading PERFEPA.BO
PERFEPA: saved
Downloading AMBIT.BO
AMBIT: saved
Downloading VISIONCINE.BO
VISIONCINE: saved
Downloading AEIM.BO
AEIM: saved
Downloading INDRANIB.BO
INDRANIB: saved
Downloading EUROLED.BO
EUROLED: saved
Downloading WINSOMBR.BO
WINSOMBR: saved
Downloading ELEFLOR.BO
ELEFLOR: saved
Downloading SKYIND.BO
SKYIND: saved
Downloading PHOENXINTL.BO
PHOENXINTL: saved
Downloading BHUDEVI.BO
BHUDEVI: saved
Downloading PRATIK.BO
PRATIK: saved
Downloading RISHIROOP.BO
RISHIROOP: saved
Downloading PROMACT.BO
PROMACT: saved
Downloading STRGRENWO.BO
STRGRENWO: saved
Downloading SYSTMTXC.BO
SYSTMTXC: saved
Downloading SHAHISHIP.BO
SHAHISHIP: saved
Downloading ALPINEHOU.BO
ALPINEHOU: saved
Downloading WWALUM.BO
WWALUM: saved
Downloading IIRM.BO
IIRM: saved
Downloading SFPIL.BO
SFPIL: saved
Downloading SGLRES.BO
SGLRES: saved
Downloading CHOKSILA.BO
CHOKSILA: saved
Downloading CCHHL.BO
CCHHL: saved
Downloading SALGUTI.BO
SALGUTI: saved
Downloading MIDWEST.BO
MIDWEST: saved
Downloading ENTRINT.BO
ENTRINT: saved
Downloading TPLPLASTEH.BO
TPLPLASTEH: saved
Downloading WIMPLAST.BO
WIMPLAST: saved
Downloading PHOTOQUP.BO
PHOTOQUP: saved
Downloading LIBERTSHOE.BO
LIBERTSHOE: saved
Downloading LIPPISYS.BO
LIPPISYS: saved
Downloading ELECTHERM.BO
ELECTHERM: saved
Downloading BLUEDART.BO
BLUEDART: saved
Downloading EXPOEAPL.BO
EXPOEAPL: saved
Downloading NATPLAS.BO
NATPLAS: saved
Downloading MFLINDIA.BO
MFLINDIA: saved
Downloading AJWAFUN.BO
AJWAFUN: saved
Downloading TEXELIN.BO
TEXELIN: saved
Downloading RAYALEMA.BO
RAYALEMA: saved
Downloading MIRZAINT.BO
MIRZAINT: saved
Downloading TFCILTD.BO
TFCILTD: saved
Downloading THAKDEV.BO
THAKDEV: saved
Downloading ARENTERP.BO
ARENTERP: saved
Downloading BIL.BO
BIL: saved
Downloading KAMATHOTEL.BO
KAMATHOTEL: saved
Downloading TIRTPLS.BO
TIRTPLS: saved
Downloading KEEPLEARN.BO
KEEPLEARN: saved
Downloading ECOPLAST.BO
ECOPLAST: saved
Downloading ELEMARB.BO
ELEMARB: saved
Downloading BITS.BO
BITS: saved
Downloading ADARSHPL.BO
ADARSHPL: saved
Downloading HPBL.BO
HPBL: saved
Downloading NICCOPAR.BO
NICCOPAR: saved
Downloading NTCIND.BO
NTCIND: saved
Downloading SANDESH.BO
SANDESH: saved
Downloading GARNET.BO
GARNET: saved
Downloading GOLDIAM.BO
GOLDIAM: saved
Downloading BRIGHTBR.BO
BRIGHTBR: saved
Downloading SHAWGELTIN.BO
SHAWGELTIN: saved
Downloading PGFOILQ.BO
PGFOILQ: saved
Downloading GRATEXI.BO
GRATEXI: saved
Downloading VELHO.BO
VELHO: saved
Downloading HOWARHO.BO
HOWARHO: saved
Downloading VALIANT.BO
VALIANT: saved
Downloading DRAGARWQ.BO
DRAGARWQ: saved
Downloading MHSGRMS.BO
MHSGRMS: saved
Downloading GREENPLY.BO
GREENPLY: saved
Downloading SEAMECLTD.BO
SEAMECLTD: saved
Downloading RAGHUNAT.BO
RAGHUNAT: saved
Downloading CHEVIOT.BO
CHEVIOT: saved
Downloading DAICHI.BO
DAICHI: saved
Downloading RAJINFRA.BO
RAJINFRA: saved
Downloading SPICEISLIN.BO
SPICEISLIN: saved
Downloading CONFIPET.BO
CONFIPET: saved
Downloading SIPL.BO
SIPL: saved
Downloading SHAKTIPR.BO
SHAKTIPR: saved
Downloading ASHSI.BO
ASHSI: saved
Downloading BANARBEADS.BO
BANARBEADS: saved
Downloading AREXMIS.BO
AREXMIS: saved
Downloading BI.BO
BI: saved
Downloading ISFL.BO
ISFL: saved
Downloading RISHILASE.BO
RISHILASE: saved
Downloading JAINCO.BO
JAINCO: saved
Downloading KUMPFIN.BO
KUMPFIN: saved
Downloading INTECCAP.BO
INTECCAP: saved
Downloading RAJSEC.BO
RAJSEC: saved
Downloading SIDDHEGA.BO
SIDDHEGA: saved
Downloading 63MOONS.BO
63MOONS: saved
Downloading SHIKHAR.BO
SHIKHAR: saved
Downloading SARLAPOLY.BO
SARLAPOLY: saved
Downloading INDOCRED.BO
INDOCRED: saved
Downloading MKTCREAT.BO
MKTCREAT: saved
Downloading HFIL.BO
HFIL: saved
Downloading SONALAD.BO
SONALAD: saved
Downloading PADMAIND.BO
PADMAIND: saved
Downloading 21STCENMGM.BO
21STCENMGM: saved
Downloading HRYNSHP.BO
HRYNSHP: saved
Downloading KALIND.BO
KALIND: saved
Downloading VAICC.BO
VAICC: saved
Downloading TYROON.BO
TYROON: saved
Downloading LAOPALA.BO
LAOPALA: saved
Downloading STYLAMIND.BO
STYLAMIND: saved
Downloading VENUSREM.BO
VENUSREM: saved
Downloading LASTMILE.BO
LASTMILE: saved
Downloading GUJCRAFT.BO
GUJCRAFT: saved
Downloading HEERAISP.BO
HEERAISP: saved
Downloading DHOOTIN.BO
DHOOTIN: saved
Downloading CRIMSON.BO
CRIMSON: saved
Downloading SHBAJRG.BO
SHBAJRG: saved
Downloading URJA.BO
URJA: saved
Downloading ASHAPURMIN.BO
ASHAPURMIN: saved
Downloading SHREEPAC.BO
SHREEPAC: saved
Downloading GUJALKALI.BO
GUJALKALI: saved
Downloading INDIACEM.BO
INDIACEM: saved
Downloading JKTYRE.BO
JKTYRE: saved
Downloading SIL.BO
SIL: saved
Downloading JUBLPHARMA.BO
JUBLPHARMA: saved
Downloading THEINVEST.BO
THEINVEST: saved
Downloading SAMYAKINT.BO
SAMYAKINT: saved
Downloading AADIIND.BO
AADIIND: saved
Downloading SPARKLEGR.BO
SPARKLEGR: saved
Downloading ACKNIT.BO
ACKNIT: saved
Downloading TITANSEC.BO
TITANSEC: saved
Downloading REALECO.BO
REALECO: saved
Downloading VIVANZA.BO
VIVANZA: saved
Downloading YASHRAJC.BO
YASHRAJC: saved
Downloading LORDSHOTL.BO
LORDSHOTL: saved
Downloading CSLFINANCE.BO
CSLFINANCE: saved
Downloading SANGHVIMOV.BO
SANGHVIMOV: saved
Downloading ANTELOPUS.BO
ANTELOPUS: saved
Downloading PURETROP.BO
PURETROP: saved
Downloading FAZE3Q.BO
FAZE3Q: saved
Downloading ANUPAM.BO
ANUPAM: saved
Downloading RAJPACK.BO
RAJPACK: saved
Downloading PRIVISCL.BO
PRIVISCL: saved
Downloading NATRAJPR.BO
NATRAJPR: saved
Downloading SAMRATPH.BO
SAMRATPH: saved
Downloading NPRFIN.BO
NPRFIN: saved
Downloading NILE.BO
NILE: saved
Downloading AMCOIND.BO
AMCOIND: saved
Downloading OPTIEMUS.BO
OPTIEMUS: saved
Downloading KREONFIN.BO
KREONFIN: saved
Downloading GYANDEV.BO
GYANDEV: saved
Downloading KISAN.BO
KISAN: saved
Downloading KERALAYUR.BO
KERALAYUR: saved
Downloading MONGIPA.BO
MONGIPA: saved
Downloading MOHITPPR.BO
MOHITPPR: saved
Downloading DAULAT.BO
DAULAT: saved
Downloading ODYSSEY.BO
ODYSSEY: saved
Downloading VKGLOBAL.BO
VKGLOBAL: saved
Downloading RSCINT.BO
RSCINT: saved
Downloading SURATRAML.BO
SURATRAML: saved
Downloading ATHARVENT.BO
ATHARVENT: saved
Downloading FUNDVISER.BO
FUNDVISER: saved
Downloading THEMISMED.BO
THEMISMED: saved
Downloading KALLAM.BO
KALLAM: saved
Downloading BRAWN.BO
BRAWN: saved
Downloading FORINTL.BO
FORINTL: saved
Downloading KINGSINFR.BO
KINGSINFR: saved
Downloading SWOJAS.BO
SWOJAS: saved
Downloading SUBSM.BO
SUBSM: saved
Downloading AUROLAB.BO
AUROLAB: saved
Downloading KJMCFIN.BO
KJMCFIN: saved
Downloading SUVEN.BO
SUVEN: saved
Downloading ARYAMAN.BO
ARYAMAN: saved
Downloading BRIDGESE.BO
BRIDGESE: saved
Downloading RISAINTL.BO
RISAINTL: saved
Downloading RAJTUBE.BO
RAJTUBE: saved
Downloading KAYPOWR.BO
KAYPOWR: saved
Downloading INTSTOIL.BO
INTSTOIL: saved
Downloading GLOBALCA.BO
GLOBALCA: saved
Downloading SAINIK.BO
SAINIK: saved
Downloading ARIGATO.BO
ARIGATO: saved
Downloading RICHUNV.BO
RICHUNV: saved
Downloading QUANTDIA.BO
QUANTDIA: saved
Downloading SPCAPIT.BO
SPCAPIT: saved
Downloading PAOS.BO
PAOS: saved
Downloading SHRAJOI.BO
SHRAJOI: saved
Downloading KOTHARIPRO.BO
KOTHARIPRO: saved
Downloading PICCADIL.BO
PICCADIL: saved
Downloading CLSEL.BO
CLSEL: saved
Downloading CHANDRAP.BO
CHANDRAP: saved
Downloading KIMIABL.BO
KIMIABL: saved
Downloading HINDTIN.BO
HINDTIN: saved
Downloading GODAVARI.BO
GODAVARI: saved
Downloading PREMCO.BO
PREMCO: saved
Downloading MUKESHB.BO
MUKESHB: saved
Downloading GENUSPOWER.BO
GENUSPOWER: saved
Downloading ASIANENE.BO
ASIANENE: saved
Downloading KBSINDIA.BO
KBSINDIA: saved
Downloading PRABHHANS.BO
PRABHHANS: saved
Downloading UGARSUGAR.BO
UGARSUGAR: saved
Downloading ORIENTBELL.BO
ORIENTBELL: saved
Downloading NRBBEARING.BO
NRBBEARING: saved
Downloading VAMSHIRU.BO
VAMSHIRU: saved
Downloading NILAINFRA.BO
NILAINFRA: saved
Downloading DBSTOCKBRO.BO
DBSTOCKBRO: saved
Downloading VINYOFL.BO
VINYOFL: saved
Downloading JINDCAP.BO
JINDCAP: saved
Downloading EPIC.BO
EPIC: saved
Downloading SUMEDHA.BO
SUMEDHA: saved
Downloading KUWERIN.BO
KUWERIN: saved
Downloading CHOKSI.BO
CHOKSI: saved
Downloading ASHISHPO.BO
ASHISHPO: saved
Downloading SHIVAAGRO.BO
SHIVAAGRO: saved
Downloading SIDDHA.BO
SIDDHA: saved
Downloading KIRANSY-B.BO
KIRANSY-B: saved
Downloading SUMERUIND.BO
SUMERUIND: saved
Downloading RUNGTAIR.BO
RUNGTAIR: saved
Downloading GTTDATA.BO
GTTDATA: saved
Downloading VALSONQ.BO
VALSONQ: saved
Downloading SABOOSOD.BO
SABOOSOD: saved
Downloading GSLSEC.BO
GSLSEC: saved
Downloading TINNARUBR.BO
TINNARUBR: saved
Downloading VIKRAMTH.BO
VIKRAMTH: saved
Downloading STRATMONT.BO
STRATMONT: saved
Downloading AKCAPIT.BO
AKCAPIT: saved
Downloading RELAXO.BO
RELAXO: saved
Downloading VIRAT.BO
VIRAT: saved
Downloading RRETAIL.BO
RRETAIL: saved
Downloading TERAI.BO
TERAI: saved
Downloading MANRAJH.BO
MANRAJH: saved
Downloading COSCO.BO
COSCO: saved
Downloading KENFIN.BO
KENFIN: saved
Downloading SHILPAMED.BO
SHILPAMED: saved
Downloading PARACABLES.BO
PARACABLES: saved
Downloading NCLRESE.BO
NCLRESE: saved
Downloading EXPLICITFIN.BO
EXPLICITFIN: saved
Downloading LADDERUP.BO
LADDERUP: saved
Downloading UYFINCORP.BO
UYFINCORP: saved
Downloading EKAMLEA.BO
EKAMLEA: saved
Downloading SWASTIKA.BO
SWASTIKA: saved
Downloading PRIMAPLA.BO
PRIMAPLA: saved
Downloading TELECANOR.BO
TELECANOR: saved
Downloading JAGSONSER.BO
JAGSONSER: saved
Downloading GARGFUR.BO
GARGFUR: saved
Downloading SAMPRE.BO
SAMPRE: saved
Downloading AAIL.BO
AAIL: saved
Downloading VIPULORG.BO
VIPULORG: saved
Downloading ECORECO.BO
ECORECO: saved
Downloading GOODLUCK.BO
GOODLUCK: saved
Downloading GOYALASS.BO
GOYALASS: saved
Downloading ZENITHHE.BO
ZENITHHE: saved
Downloading YORKEXP.BO
YORKEXP: saved
Downloading SUPREME.BO
SUPREME: saved
Downloading LYKISLTD.BO
LYKISLTD: saved
Downloading PRIMEPRO.BO
PRIMEPRO: saved
Downloading ZENLABS.BO
ZENLABS: saved
Downloading RAJRILTD.BO
RAJRILTD: saved
Downloading ANIRIT.BO
ANIRIT: saved
Downloading GOWRALE.BO
GOWRALE: saved
Downloading JAGANLAM.BO
JAGANLAM: saved
Downloading ASITCFIN.BO
ASITCFIN: saved
Downloading ENCODE.BO
ENCODE: saved
Downloading SUPERBAK.BO
SUPERBAK: saved
Downloading OVOBELE.BO
OVOBELE: saved
Downloading ACSTECH.BO
ACSTECH: saved
Downloading CHALLANI.BO
CHALLANI: saved
Downloading CORNE.BO
CORNE: saved
Downloading SHENTRA.BO
SHENTRA: saved
Downloading STERTOOLS.BO
STERTOOLS: saved
Downloading AGARWAL.BO
AGARWAL: saved
Downloading DYNAMICP.BO
DYNAMICP: saved
Downloading INLANPR.BO
INLANPR: saved
Downloading CEEJAY.BO
CEEJAY: saved
Downloading SUNCITYSY.BO
SUNCITYSY: saved
Downloading SHGANEL.BO
SHGANEL: saved
Downloading ANNAINFRA.BO
ANNAINFRA: saved
Downloading BHAGERIA.BO
BHAGERIA: saved
Downloading OIVL.BO
OIVL: saved
Downloading BNRUDY.BO
BNRUDY: saved
Downloading KRBL.BO
KRBL: saved
Downloading SSPDL.BO
SSPDL: saved
Downloading DAIKAFFI.BO
DAIKAFFI: saved
Downloading CILSEC.BO
CILSEC: saved
Downloading CLIOINFO.BO
CLIOINFO: saved
Downloading CUPID.BO
CUPID: saved
Downloading SUNSHIEL.BO
SUNSHIEL: saved
Downloading HIPOLIN.BO
HIPOLIN: saved
Downloading GDLLEAS.BO
GDLLEAS: saved
Downloading CHEMBOND.BO
CHEMBOND: saved
Downloading CIFL.BO
CIFL: saved
Downloading ABVL.BO
ABVL: saved
Downloading SUCROSA.BO
SUCROSA: saved
Downloading NGIND.BO
NGIND: saved
Downloading ASIAPAK.BO
ASIAPAK: saved
Downloading SICAPIT.BO
SICAPIT: saved

$KCL.BO: possibly delisted; no timezone found

1 Failed download:
['KCL.BO']: possibly delisted; no timezone found
$08ADD.BO: possibly delisted; no timezone found

1 Failed download:
['08ADD.BO']: possibly delisted; no timezone found
$ISIFHLSG.BO: possibly delisted; no timezone found

1 Failed download:
['ISIFHLSG.BO']: possibly delisted; no timezone found

## **NSE Block deals**

In [2]:
%pip install nselib

Collecting nselib
  Downloading nselib-2.5.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from nselib) (2.32.5)
Requirement already satisfied: pandas in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from nselib) (2.3.3)
Requirement already satisfied: scipy in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from nselib) (1.16.3)
Collecting pandas_market_calendars (from nselib)
  Downloading pandas_market_calendars-5.4.0-py3-none-any.whl.metadata (8.8 kB)
Collecting pypdf (from nselib)
  Downloading pypdf-6.12.2-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas->nselib) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas->nselib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas->nselib) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from pandas->nselib) (2025.3)
Requirement already satisfied: six>=1.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->nselib) (1.17.0)
Collecting exchange-calendars>=3.3 (from pandas_market_calendars->nselib)
  Downloading exchange_calendars-4.13.2-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: pyluach>=2.3.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from exchange-calendars>=3.3->pandas_market_calendars->nselib) (2.3.0)
Requirement already satisfied: toolz>=1.0.0 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from exchange-calendars>=3.3->pandas_market_calendars->nselib) (1.1.0)
Collecting korean_lunar_calendar>=0.3.1 (from exchange-calendars>=3.3->pandas_market_calendars->nselib)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests->nselib) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests->nselib) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests->nselib) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/trusted-service-user/jupyter-env/python3.12/lib/python3.12/site-packages (from requests->nselib) (2025.10.5)
Downloading nselib-2.5.1-py3-none-any.whl (56 kB)
Downloading pandas_market_calendars-5.4.0-py3-none-any.whl (134 kB)
Downloading exchange_calendars-4.13.2-py3-none-any.whl (213 kB)
Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Downloading pypdf-6.12.2-py3-none-any.whl (343 kB)
Installing collected packages: korean_lunar_calendar, pypdf, exchange-calendars, pandas_market_calendars, nselib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [nselib]2m4/5 [nselib]e-calendars]
Successfully installed exchange-calendars-4.13.2 korean_lunar_calendar-0.3.1 nselib-2.5.1 pandas_market_calendars-5.4.0 pypdf-6.12.2
Note: you may need to restart the kernel to use updated packages.

In [19]:
from nselib import capital_market
print("nselib working")

nselib working

In [26]:
import pandas as pd
import os
from datetime import datetime, timedelta
from nselib import capital_market


SAVE_DIR = "/lakehouse/default/Files/data/raw/nse_block_hist"
os.makedirs(SAVE_DIR, exist_ok=True)

all_data = []

start_date = datetime(2001, 1, 1)
end_date = datetime.today()


current_start = start_date

while current_start <= end_date:

    current_end = current_start + timedelta(days=6)

    if current_end > end_date:
        current_end = end_date

    from_dt = current_start.strftime("%d-%m-%Y")
    to_dt = current_end.strftime("%d-%m-%Y")

    print(f"Fetching {from_dt} → {to_dt}")

    try:
        data = capital_market.block_deals_data(
            from_date=from_dt,
            to_date=to_dt
        )

        df_chunk = pd.DataFrame(data)

        print(f"Rows: {len(df_chunk)}")

        all_data.append(df_chunk)

    except Exception as e:
        print(f"ERROR -> {e}")

    current_start = current_end + timedelta(days=1)


# Combine all chunks
df = pd.concat(all_data, ignore_index=True)

print("Total rows:", len(df))


today = datetime.today().strftime("%d-%m-%Y")

file_name = f"blockdeals_{today}.csv"

file_path = os.path.join(
    SAVE_DIR,
    file_name
)

df.to_csv(file_path, index=False)

print("Saved:", file_path)

Fetching 01-01-2001 → 07-01-2001
Rows: 0
Fetching 08-01-2001 → 14-01-2001
Rows: 0
Fetching 15-01-2001 → 21-01-2001
Rows: 0
Fetching 22-01-2001 → 28-01-2001
Rows: 0
Fetching 29-01-2001 → 04-02-2001
Rows: 0
Fetching 05-02-2001 → 11-02-2001
Rows: 0
Fetching 12-02-2001 → 18-02-2001
Rows: 0
Fetching 19-02-2001 → 25-02-2001
Rows: 0
Fetching 26-02-2001 → 04-03-2001
Rows: 0
Fetching 05-03-2001 → 11-03-2001
Rows: 0
Fetching 12-03-2001 → 18-03-2001
Rows: 0
Fetching 19-03-2001 → 25-03-2001
Rows: 0
Fetching 26-03-2001 → 01-04-2001
Rows: 0
Fetching 02-04-2001 → 08-04-2001
Rows: 0
Fetching 09-04-2001 → 15-04-2001
Rows: 0
Fetching 16-04-2001 → 22-04-2001
Rows: 0
Fetching 23-04-2001 → 29-04-2001
Rows: 0
Fetching 30-04-2001 → 06-05-2001
Rows: 0
Fetching 07-05-2001 → 13-05-2001
Rows: 0
Fetching 14-05-2001 → 20-05-2001
Rows: 0
Fetching 21-05-2001 → 27-05-2001
Rows: 0
Fetching 28-05-2001 → 03-06-2001
Rows: 0
Fetching 04-06-2001 → 10-06-2001
Rows: 0
Fetching 11-06-2001 → 17-06-2001
Rows: 0
Fetching 18-06-2001 → 24-06-2001
Rows: 0
Fetching 25-06-2001 → 01-07-2001
Rows: 0
Fetching 02-07-2001 → 08-07-2001
Rows: 0
Fetching 09-07-2001 → 15-07-2001
Rows: 0
Fetching 16-07-2001 → 22-07-2001
Rows: 0
Fetching 23-07-2001 → 29-07-2001
Rows: 0
Fetching 30-07-2001 → 05-08-2001
Rows: 0
Fetching 06-08-2001 → 12-08-2001
Rows: 0
Fetching 13-08-2001 → 19-08-2001
Rows: 0
Fetching 20-08-2001 → 26-08-2001
Rows: 0
Fetching 27-08-2001 → 02-09-2001
Rows: 0
Fetching 03-09-2001 → 09-09-2001
Rows: 0
Fetching 10-09-2001 → 16-09-2001
Rows: 0
Fetching 17-09-2001 → 23-09-2001
Rows: 0
Fetching 24-09-2001 → 30-09-2001
Rows: 0
Fetching 01-10-2001 → 07-10-2001
Rows: 0
Fetching 08-10-2001 → 14-10-2001
Rows: 0
Fetching 15-10-2001 → 21-10-2001
Rows: 0
Fetching 22-10-2001 → 28-10-2001
Rows: 0
Fetching 29-10-2001 → 04-11-2001
Rows: 0
Fetching 05-11-2001 → 11-11-2001
Rows: 0
Fetching 12-11-2001 → 18-11-2001
Rows: 0
Fetching 19-11-2001 → 25-11-2001
Rows: 0
Fetching 26-11-2001 → 02-12-2001
Rows: 0
Fetching 03-12-2001 → 09-12-2001
Rows: 0
Fetching 10-12-2001 → 16-12-2001
Rows: 0
Fetching 17-12-2001 → 23-12-2001
Rows: 0
Fetching 24-12-2001 → 30-12-2001
Rows: 0
Fetching 31-12-2001 → 06-01-2002
Rows: 0
Fetching 07-01-2002 → 13-01-2002
Rows: 0
Fetching 14-01-2002 → 20-01-2002
Rows: 0
Fetching 21-01-2002 → 27-01-2002
Rows: 0
Fetching 28-01-2002 → 03-02-2002
Rows: 0
Fetching 04-02-2002 → 10-02-2002
Rows: 0
Fetching 11-02-2002 → 17-02-2002
Rows: 0
Fetching 18-02-2002 → 24-02-2002
Rows: 0
Fetching 25-02-2002 → 03-03-2002
Rows: 0
Fetching 04-03-2002 → 10-03-2002
Rows: 0
Fetching 11-03-2002 → 17-03-2002
Rows: 0
Fetching 18-03-2002 → 24-03-2002
Rows: 0
Fetching 25-03-2002 → 31-03-2002
Rows: 0
Fetching 01-04-2002 → 07-04-2002
Rows: 0
Fetching 08-04-2002 → 14-04-2002
Rows: 0
Fetching 15-04-2002 → 21-04-2002
Rows: 0
Fetching 22-04-2002 → 28-04-2002
Rows: 0
Fetching 29-04-2002 → 05-05-2002
Rows: 0
Fetching 06-05-2002 → 12-05-2002
Rows: 0
Fetching 13-05-2002 → 19-05-2002
Rows: 0
Fetching 20-05-2002 → 26-05-2002
Rows: 0
Fetching 27-05-2002 → 02-06-2002
Rows: 0
Fetching 03-06-2002 → 09-06-2002
Rows: 0
Fetching 10-06-2002 → 16-06-2002
Rows: 0
Fetching 17-06-2002 → 23-06-2002
Rows: 0
Fetching 24-06-2002 → 30-06-2002
Rows: 0
Fetching 01-07-2002 → 07-07-2002
Rows: 0
Fetching 08-07-2002 → 14-07-2002
Rows: 0
Fetching 15-07-2002 → 21-07-2002
Rows: 0
Fetching 22-07-2002 → 28-07-2002
Rows: 0
Fetching 29-07-2002 → 04-08-2002
Rows: 0
Fetching 05-08-2002 → 11-08-2002
Rows: 0
Fetching 12-08-2002 → 18-08-2002
Rows: 0
Fetching 19-08-2002 → 25-08-2002
Rows: 0
Fetching 26-08-2002 → 01-09-2002
Rows: 0
Fetching 02-09-2002 → 08-09-2002
Rows: 0
Fetching 09-09-2002 → 15-09-2002
Rows: 0
Fetching 16-09-2002 → 22-09-2002
Rows: 0
Fetching 23-09-2002 → 29-09-2002
Rows: 0
Fetching 30-09-2002 → 06-10-2002
Rows: 0
Fetching 07-10-2002 → 13-10-2002
Rows: 0
Fetching 14-10-2002 → 20-10-2002
Rows: 0
Fetching 21-10-2002 → 27-10-2002
Rows: 0
Fetching 28-10-2002 → 03-11-2002
Rows: 0
Fetching 04-11-2002 → 10-11-2002
Rows: 0
Fetching 11-11-2002 → 17-11-2002
Rows: 0
Fetching 18-11-2002 → 24-11-2002
Rows: 0
Fetching 25-11-2002 → 01-12-2002
Rows: 0
Fetching 02-12-2002 → 08-12-2002
Rows: 0
Fetching 09-12-2002 → 15-12-2002
Rows: 0
Fetching 16-12-2002 → 22-12-2002
Rows: 0
Fetching 23-12-2002 → 29-12-2002
Rows: 0
Fetching 30-12-2002 → 05-01-2003
Rows: 0
Fetching 06-01-2003 → 12-01-2003
Rows: 0
Fetching 13-01-2003 → 19-01-2003
Rows: 0
Fetching 20-01-2003 → 26-01-2003
Rows: 0
Fetching 27-01-2003 → 02-02-2003
Rows: 0
Fetching 03-02-2003 → 09-02-2003
Rows: 0
Fetching 10-02-2003 → 16-02-2003
Rows: 0
Fetching 17-02-2003 → 23-02-2003
Rows: 0
Fetching 24-02-2003 → 02-03-2003
Rows: 0
Fetching 03-03-2003 → 09-03-2003
Rows: 0
Fetching 10-03-2003 → 16-03-2003
Rows: 0
Fetching 17-03-2003 → 23-03-2003
Rows: 0
Fetching 24-03-2003 → 30-03-2003
Rows: 0
Fetching 31-03-2003 → 06-04-2003
Rows: 0
Fetching 07-04-2003 → 13-04-2003
Rows: 0
Fetching 14-04-2003 → 20-04-2003
Rows: 0
Fetching 21-04-2003 → 27-04-2003
Rows: 0
Fetching 28-04-2003 → 04-05-2003
Rows: 0
Fetching 05-05-2003 → 11-05-2003
Rows: 0
Fetching 12-05-2003 → 18-05-2003
Rows: 0
Fetching 19-05-2003 → 25-05-2003
Rows: 0
Fetching 26-05-2003 → 01-06-2003
Rows: 0
Fetching 02-06-2003 → 08-06-2003
Rows: 0
Fetching 09-06-2003 → 15-06-2003
Rows: 0
Fetching 16-06-2003 → 22-06-2003
Rows: 0
Fetching 23-06-2003 → 29-06-2003
Rows: 0
Fetching 30-06-2003 → 06-07-2003
Rows: 0
Fetching 07-07-2003 → 13-07-2003
Rows: 0
Fetching 14-07-2003 → 20-07-2003
Rows: 0
Fetching 21-07-2003 → 27-07-2003
Rows: 0
Fetching 28-07-2003 → 03-08-2003
Rows: 0
Fetching 04-08-2003 → 10-08-2003
Rows: 0
Fetching 11-08-2003 → 17-08-2003
Rows: 0
Fetching 18-08-2003 → 24-08-2003
Rows: 0
Fetching 25-08-2003 → 31-08-2003
Rows: 0
Fetching 01-09-2003 → 07-09-2003
Rows: 0
Fetching 08-09-2003 → 14-09-2003
Rows: 0
Fetching 15-09-2003 → 21-09-2003
Rows: 0
Fetching 22-09-2003 → 28-09-2003
Rows: 0
Fetching 29-09-2003 → 05-10-2003
Rows: 0
Fetching 06-10-2003 → 12-10-2003
Rows: 0
Fetching 13-10-2003 → 19-10-2003
Rows: 0
Fetching 20-10-2003 → 26-10-2003
Rows: 0
Fetching 27-10-2003 → 02-11-2003
Rows: 0
Fetching 03-11-2003 → 09-11-2003
Rows: 0
Fetching 10-11-2003 → 16-11-2003
Rows: 0
Fetching 17-11-2003 → 23-11-2003
Rows: 0
Fetching 24-11-2003 → 30-11-2003
Rows: 0
Fetching 01-12-2003 → 07-12-2003
Rows: 0
Fetching 08-12-2003 → 14-12-2003
Rows: 0
Fetching 15-12-2003 → 21-12-2003
Rows: 0
Fetching 22-12-2003 → 28-12-2003
Rows: 0
Fetching 29-12-2003 → 04-01-2004
Rows: 0
Fetching 05-01-2004 → 11-01-2004
Rows: 0
Fetching 12-01-2004 → 18-01-2004
Rows: 0
Fetching 19-01-2004 → 25-01-2004
Rows: 0
Fetching 26-01-2004 → 01-02-2004
Rows: 0
Fetching 02-02-2004 → 08-02-2004
Rows: 0
Fetching 09-02-2004 → 15-02-2004
Rows: 0
Fetching 16-02-2004 → 22-02-2004
Rows: 0
Fetching 23-02-2004 → 29-02-2004
Rows: 0
Fetching 01-03-2004 → 07-03-2004
Rows: 0
Fetching 08-03-2004 → 14-03-2004
Rows: 0
Fetching 15-03-2004 → 21-03-2004
Rows: 0
Fetching 22-03-2004 → 28-03-2004
Rows: 0
Fetching 29-03-2004 → 04-04-2004
Rows: 0
Fetching 05-04-2004 → 11-04-2004
Rows: 0
Fetching 12-04-2004 → 18-04-2004
Rows: 0
Fetching 19-04-2004 → 25-04-2004
Rows: 0
Fetching 26-04-2004 → 02-05-2004
Rows: 0
Fetching 03-05-2004 → 09-05-2004
Rows: 0
Fetching 10-05-2004 → 16-05-2004
Rows: 0
Fetching 17-05-2004 → 23-05-2004
Rows: 0
Fetching 24-05-2004 → 30-05-2004
Rows: 0
Fetching 31-05-2004 → 06-06-2004
Rows: 0
Fetching 07-06-2004 → 13-06-2004
Rows: 0
Fetching 14-06-2004 → 20-06-2004
Rows: 0
Fetching 21-06-2004 → 27-06-2004
Rows: 0
Fetching 28-06-2004 → 04-07-2004
Rows: 0
Fetching 05-07-2004 → 11-07-2004
Rows: 0
Fetching 12-07-2004 → 18-07-2004
Rows: 0
Fetching 19-07-2004 → 25-07-2004
Rows: 0
Fetching 26-07-2004 → 01-08-2004
Rows: 0
Fetching 02-08-2004 → 08-08-2004
Rows: 0
Fetching 09-08-2004 → 15-08-2004
Rows: 0
Fetching 16-08-2004 → 22-08-2004
Rows: 0
Fetching 23-08-2004 → 29-08-2004
Rows: 0
Fetching 30-08-2004 → 05-09-2004
Rows: 0
Fetching 06-09-2004 → 12-09-2004
Rows: 0
Fetching 13-09-2004 → 19-09-2004
Rows: 0
Fetching 20-09-2004 → 26-09-2004
Rows: 0
Fetching 27-09-2004 → 03-10-2004
Rows: 0
Fetching 04-10-2004 → 10-10-2004
Rows: 0
Fetching 11-10-2004 → 17-10-2004
Rows: 0
Fetching 18-10-2004 → 24-10-2004
Rows: 0
Fetching 25-10-2004 → 31-10-2004
Rows: 0
Fetching 01-11-2004 → 07-11-2004
Rows: 0
Fetching 08-11-2004 → 14-11-2004
Rows: 0
Fetching 15-11-2004 → 21-11-2004
Rows: 0
Fetching 22-11-2004 → 28-11-2004
Rows: 0
Fetching 29-11-2004 → 05-12-2004
Rows: 0
Fetching 06-12-2004 → 12-12-2004
Rows: 0
Fetching 13-12-2004 → 19-12-2004
Rows: 0
Fetching 20-12-2004 → 26-12-2004
Rows: 0
Fetching 27-12-2004 → 02-01-2005
Rows: 0
Fetching 03-01-2005 → 09-01-2005
Rows: 0
Fetching 10-01-2005 → 16-01-2005
Rows: 0
Fetching 17-01-2005 → 23-01-2005
Rows: 0
Fetching 24-01-2005 → 30-01-2005
Rows: 0
Fetching 31-01-2005 → 06-02-2005
Rows: 0
Fetching 07-02-2005 → 13-02-2005
Rows: 0
Fetching 14-02-2005 → 20-02-2005
Rows: 0
Fetching 21-02-2005 → 27-02-2005
Rows: 0
Fetching 28-02-2005 → 06-03-2005
Rows: 0
Fetching 07-03-2005 → 13-03-2005
Rows: 0
Fetching 14-03-2005 → 20-03-2005
Rows: 0
Fetching 21-03-2005 → 27-03-2005
Rows: 0
Fetching 28-03-2005 → 03-04-2005
Rows: 0
Fetching 04-04-2005 → 10-04-2005
Rows: 0
Fetching 11-04-2005 → 17-04-2005
Rows: 0
Fetching 18-04-2005 → 24-04-2005
Rows: 0
Fetching 25-04-2005 → 01-05-2005
Rows: 0
Fetching 02-05-2005 → 08-05-2005
Rows: 0
Fetching 09-05-2005 → 15-05-2005
Rows: 0
Fetching 16-05-2005 → 22-05-2005
Rows: 0
Fetching 23-05-2005 → 29-05-2005
Rows: 0
Fetching 30-05-2005 → 05-06-2005
Rows: 0
Fetching 06-06-2005 → 12-06-2005
Rows: 0
Fetching 13-06-2005 → 19-06-2005
Rows: 0
Fetching 20-06-2005 → 26-06-2005
Rows: 0
Fetching 27-06-2005 → 03-07-2005
Rows: 0
Fetching 04-07-2005 → 10-07-2005
Rows: 0
Fetching 11-07-2005 → 17-07-2005
Rows: 0
Fetching 18-07-2005 → 24-07-2005
Rows: 0
Fetching 25-07-2005 → 31-07-2005
Rows: 0
Fetching 01-08-2005 → 07-08-2005
Rows: 0
Fetching 08-08-2005 → 14-08-2005
Rows: 0
Fetching 15-08-2005 → 21-08-2005
Rows: 0
Fetching 22-08-2005 → 28-08-2005
Rows: 0
Fetching 29-08-2005 → 04-09-2005
Rows: 0
Fetching 05-09-2005 → 11-09-2005
Rows: 0
Fetching 12-09-2005 → 18-09-2005
Rows: 0
Fetching 19-09-2005 → 25-09-2005
Rows: 0
Fetching 26-09-2005 → 02-10-2005
Rows: 0
Fetching 03-10-2005 → 09-10-2005
Rows: 0
Fetching 10-10-2005 → 16-10-2005
Rows: 0
Fetching 17-10-2005 → 23-10-2005
Rows: 0
Fetching 24-10-2005 → 30-10-2005
Rows: 0
Fetching 31-10-2005 → 06-11-2005
Rows: 0
Fetching 07-11-2005 → 13-11-2005
Rows: 0
Fetching 14-11-2005 → 20-11-2005
Rows: 2
Fetching 21-11-2005 → 27-11-2005
Rows: 2
Fetching 28-11-2005 → 04-12-2005
Rows: 6
Fetching 05-12-2005 → 11-12-2005
Rows: 28
Fetching 12-12-2005 → 18-12-2005
Rows: 40
Fetching 19-12-2005 → 25-12-2005
Rows: 40
Fetching 26-12-2005 → 01-01-2006
Rows: 28
Fetching 02-01-2006 → 08-01-2006
Rows: 0
Fetching 09-01-2006 → 15-01-2006
Rows: 0
Fetching 16-01-2006 → 22-01-2006
Rows: 6
Fetching 23-01-2006 → 29-01-2006
Rows: 3
Fetching 30-01-2006 → 05-02-2006
Rows: 0
Fetching 06-02-2006 → 12-02-2006
Rows: 0
Fetching 13-02-2006 → 19-02-2006
Rows: 2
Fetching 20-02-2006 → 26-02-2006
Rows: 0
Fetching 27-02-2006 → 05-03-2006
Rows: 8
Fetching 06-03-2006 → 12-03-2006
Rows: 26
Fetching 13-03-2006 → 19-03-2006
Rows: 4
Fetching 20-03-2006 → 26-03-2006
Rows: 40
Fetching 27-03-2006 → 02-04-2006
Rows: 112
Fetching 03-04-2006 → 09-04-2006
Rows: 16
Fetching 10-04-2006 → 16-04-2006
Rows: 2
Fetching 17-04-2006 → 23-04-2006
Rows: 6
Fetching 24-04-2006 → 30-04-2006
Rows: 0
Fetching 01-05-2006 → 07-05-2006
Rows: 4
Fetching 08-05-2006 → 14-05-2006
Rows: 4
Fetching 15-05-2006 → 21-05-2006
Rows: 6
Fetching 22-05-2006 → 28-05-2006
Rows: 5
Fetching 29-05-2006 → 04-06-2006
Rows: 0
Fetching 05-06-2006 → 11-06-2006
Rows: 0
Fetching 12-06-2006 → 18-06-2006
Rows: 0
Fetching 19-06-2006 → 25-06-2006
Rows: 4
Fetching 26-06-2006 → 02-07-2006
Rows: 0
Fetching 03-07-2006 → 09-07-2006
Rows: 0
Fetching 10-07-2006 → 16-07-2006
Rows: 0
Fetching 17-07-2006 → 23-07-2006
Rows: 0
Fetching 24-07-2006 → 30-07-2006
Rows: 2
Fetching 31-07-2006 → 06-08-2006
Rows: 4
Fetching 07-08-2006 → 13-08-2006
Rows: 0
Fetching 14-08-2006 → 20-08-2006
Rows: 7
Fetching 21-08-2006 → 27-08-2006
Rows: 2
Fetching 28-08-2006 → 03-09-2006
Rows: 4
Fetching 04-09-2006 → 10-09-2006
Rows: 7
Fetching 11-09-2006 → 17-09-2006
Rows: 18
Fetching 18-09-2006 → 24-09-2006
Rows: 6
Fetching 25-09-2006 → 01-10-2006
Rows: 2
Fetching 02-10-2006 → 08-10-2006
Rows: 0
Fetching 09-10-2006 → 15-10-2006
Rows: 2
Fetching 16-10-2006 → 22-10-2006
Rows: 4
Fetching 23-10-2006 → 29-10-2006
Rows: 6
Fetching 30-10-2006 → 05-11-2006
Rows: 6
Fetching 06-11-2006 → 12-11-2006
Rows: 2
Fetching 13-11-2006 → 19-11-2006
Rows: 0
Fetching 20-11-2006 → 26-11-2006
Rows: 0
Fetching 27-11-2006 → 03-12-2006
Rows: 2
Fetching 04-12-2006 → 10-12-2006
Rows: 0
Fetching 11-12-2006 → 17-12-2006
Rows: 4
Fetching 18-12-2006 → 24-12-2006
Rows: 0
Fetching 25-12-2006 → 31-12-2006
Rows: 0
Fetching 01-01-2007 → 07-01-2007
Rows: 0
Fetching 08-01-2007 → 14-01-2007
Rows: 0
Fetching 15-01-2007 → 21-01-2007
Rows: 0
Fetching 22-01-2007 → 28-01-2007
Rows: 3
Fetching 29-01-2007 → 04-02-2007
Rows: 13
Fetching 05-02-2007 → 11-02-2007
Rows: 5
Fetching 12-02-2007 → 18-02-2007
Rows: 0
Fetching 19-02-2007 → 25-02-2007
Rows: 0
Fetching 26-02-2007 → 04-03-2007
Rows: 4
Fetching 05-03-2007 → 11-03-2007
Rows: 0
Fetching 12-03-2007 → 18-03-2007
Rows: 10
Fetching 19-03-2007 → 25-03-2007
Rows: 6
Fetching 26-03-2007 → 01-04-2007
Rows: 8
Fetching 02-04-2007 → 08-04-2007
Rows: 0
Fetching 09-04-2007 → 15-04-2007
Rows: 4
Fetching 16-04-2007 → 22-04-2007
Rows: 39
Fetching 23-04-2007 → 29-04-2007
Rows: 0
Fetching 30-04-2007 → 06-05-2007
Rows: 0
Fetching 07-05-2007 → 13-05-2007
Rows: 11
Fetching 14-05-2007 → 20-05-2007
Rows: 0
Fetching 21-05-2007 → 27-05-2007
Rows: 0
Fetching 28-05-2007 → 03-06-2007
Rows: 2
Fetching 04-06-2007 → 10-06-2007
Rows: 0
Fetching 11-06-2007 → 17-06-2007
Rows: 0
Fetching 18-06-2007 → 24-06-2007
Rows: 0
Fetching 25-06-2007 → 01-07-2007
Rows: 7
Fetching 02-07-2007 → 08-07-2007
Rows: 2
Fetching 09-07-2007 → 15-07-2007
Rows: 0
Fetching 16-07-2007 → 22-07-2007
Rows: 2
Fetching 23-07-2007 → 29-07-2007
Rows: 0
Fetching 30-07-2007 → 05-08-2007
Rows: 0
Fetching 06-08-2007 → 12-08-2007
Rows: 5
Fetching 13-08-2007 → 19-08-2007
Rows: 3
Fetching 20-08-2007 → 26-08-2007
Rows: 2
Fetching 27-08-2007 → 02-09-2007
Rows: 0
Fetching 03-09-2007 → 09-09-2007
Rows: 0
Fetching 10-09-2007 → 16-09-2007
Rows: 4
Fetching 17-09-2007 → 23-09-2007
Rows: 0
Fetching 24-09-2007 → 30-09-2007
Rows: 8
Fetching 01-10-2007 → 07-10-2007
Rows: 0
Fetching 08-10-2007 → 14-10-2007
Rows: 0
Fetching 15-10-2007 → 21-10-2007
Rows: 0
Fetching 22-10-2007 → 28-10-2007
Rows: 4
Fetching 29-10-2007 → 04-11-2007
Rows: 4
Fetching 05-11-2007 → 11-11-2007
Rows: 8
Fetching 12-11-2007 → 18-11-2007
Rows: 2
Fetching 19-11-2007 → 25-11-2007
Rows: 0
Fetching 26-11-2007 → 02-12-2007
Rows: 2
Fetching 03-12-2007 → 09-12-2007
Rows: 6
Fetching 10-12-2007 → 16-12-2007
Rows: 0
Fetching 17-12-2007 → 23-12-2007
Rows: 2
Fetching 24-12-2007 → 30-12-2007
Rows: 9
Fetching 31-12-2007 → 06-01-2008
Rows: 5
Fetching 07-01-2008 → 13-01-2008
Rows: 0
Fetching 14-01-2008 → 20-01-2008
Rows: 0
Fetching 21-01-2008 → 27-01-2008
Rows: 0
Fetching 28-01-2008 → 03-02-2008
Rows: 0
Fetching 04-02-2008 → 10-02-2008
Rows: 7
Fetching 11-02-2008 → 17-02-2008
Rows: 2
Fetching 18-02-2008 → 24-02-2008
Rows: 3
Fetching 25-02-2008 → 02-03-2008
Rows: 0
Fetching 03-03-2008 → 09-03-2008
Rows: 0
Fetching 10-03-2008 → 16-03-2008
Rows: 2
Fetching 17-03-2008 → 23-03-2008
Rows: 17
Fetching 24-03-2008 → 30-03-2008
Rows: 0
Fetching 31-03-2008 → 06-04-2008
Rows: 14
Fetching 07-04-2008 → 13-04-2008
Rows: 0
Fetching 14-04-2008 → 20-04-2008
Rows: 16
Fetching 21-04-2008 → 27-04-2008
Rows: 0
Fetching 28-04-2008 → 04-05-2008
Rows: 0
Fetching 05-05-2008 → 11-05-2008
Rows: 0
Fetching 12-05-2008 → 18-05-2008
Rows: 2
Fetching 19-05-2008 → 25-05-2008
Rows: 3
Fetching 26-05-2008 → 01-06-2008
Rows: 12
Fetching 02-06-2008 → 08-06-2008
Rows: 6
Fetching 09-06-2008 → 15-06-2008
Rows: 6
Fetching 16-06-2008 → 22-06-2008
Rows: 4
Fetching 23-06-2008 → 29-06-2008
Rows: 2
Fetching 30-06-2008 → 06-07-2008
Rows: 2
Fetching 07-07-2008 → 13-07-2008
Rows: 9
Fetching 14-07-2008 → 20-07-2008
Rows: 8
Fetching 21-07-2008 → 27-07-2008
Rows: 2
Fetching 28-07-2008 → 03-08-2008
Rows: 0
Fetching 04-08-2008 → 10-08-2008
Rows: 3
Fetching 11-08-2008 → 17-08-2008
Rows: 0
Fetching 18-08-2008 → 24-08-2008
Rows: 0
Fetching 25-08-2008 → 31-08-2008
Rows: 0
Fetching 01-09-2008 → 07-09-2008
Rows: 0
Fetching 08-09-2008 → 14-09-2008
Rows: 0
Fetching 15-09-2008 → 21-09-2008
Rows: 2
Fetching 22-09-2008 → 28-09-2008
Rows: 2
Fetching 29-09-2008 → 05-10-2008
Rows: 0
Fetching 06-10-2008 → 12-10-2008
Rows: 0
Fetching 13-10-2008 → 19-10-2008
Rows: 0
Fetching 20-10-2008 → 26-10-2008
Rows: 2
Fetching 27-10-2008 → 02-11-2008
Rows: 2
Fetching 03-11-2008 → 09-11-2008
Rows: 6
Fetching 10-11-2008 → 16-11-2008
Rows: 0
Fetching 17-11-2008 → 23-11-2008
Rows: 0
Fetching 24-11-2008 → 30-11-2008
Rows: 0
Fetching 01-12-2008 → 07-12-2008
Rows: 0
Fetching 08-12-2008 → 14-12-2008
Rows: 0
Fetching 15-12-2008 → 21-12-2008
Rows: 2
Fetching 22-12-2008 → 28-12-2008
Rows: 0
Fetching 29-12-2008 → 04-01-2009
Rows: 0
Fetching 05-01-2009 → 11-01-2009
Rows: 0
Fetching 12-01-2009 → 18-01-2009
Rows: 4
Fetching 19-01-2009 → 25-01-2009
Rows: 0
Fetching 26-01-2009 → 01-02-2009
Rows: 2
Fetching 02-02-2009 → 08-02-2009
Rows: 0
Fetching 09-02-2009 → 15-02-2009
Rows: 0
Fetching 16-02-2009 → 22-02-2009
Rows: 0
Fetching 23-02-2009 → 01-03-2009
Rows: 0
Fetching 02-03-2009 → 08-03-2009
Rows: 4
Fetching 09-03-2009 → 15-03-2009
Rows: 6
Fetching 16-03-2009 → 22-03-2009
Rows: 2
Fetching 23-03-2009 → 29-03-2009
Rows: 4
Fetching 30-03-2009 → 05-04-2009
Rows: 2
Fetching 06-04-2009 → 12-04-2009
Rows: 0
Fetching 13-04-2009 → 19-04-2009
Rows: 0
Fetching 20-04-2009 → 26-04-2009
Rows: 0
Fetching 27-04-2009 → 03-05-2009
Rows: 0
Fetching 04-05-2009 → 10-05-2009
Rows: 0
Fetching 11-05-2009 → 17-05-2009
Rows: 0
Fetching 18-05-2009 → 24-05-2009
Rows: 8
Fetching 25-05-2009 → 31-05-2009
Rows: 2
Fetching 01-06-2009 → 07-06-2009
Rows: 0
Fetching 08-06-2009 → 14-06-2009
Rows: 0
Fetching 15-06-2009 → 21-06-2009
Rows: 0
Fetching 22-06-2009 → 28-06-2009
Rows: 60
Fetching 29-06-2009 → 05-07-2009
Rows: 0
Fetching 06-07-2009 → 12-07-2009
Rows: 4
Fetching 13-07-2009 → 19-07-2009
Rows: 0
Fetching 20-07-2009 → 26-07-2009
Rows: 4
Fetching 27-07-2009 → 02-08-2009
Rows: 2
Fetching 03-08-2009 → 09-08-2009
Rows: 0
Fetching 10-08-2009 → 16-08-2009
Rows: 0
Fetching 17-08-2009 → 23-08-2009
Rows: 2
Fetching 24-08-2009 → 30-08-2009
Rows: 2
Fetching 31-08-2009 → 06-09-2009
Rows: 2
Fetching 07-09-2009 → 13-09-2009
Rows: 2
Fetching 14-09-2009 → 20-09-2009
Rows: 4
Fetching 21-09-2009 → 27-09-2009
Rows: 2
Fetching 28-09-2009 → 04-10-2009
Rows: 4
Fetching 05-10-2009 → 11-10-2009
Rows: 4
Fetching 12-10-2009 → 18-10-2009
Rows: 2
Fetching 19-10-2009 → 25-10-2009
Rows: 0
Fetching 26-10-2009 → 01-11-2009
Rows: 2
Fetching 02-11-2009 → 08-11-2009
Rows: 2
Fetching 09-11-2009 → 15-11-2009
Rows: 11
Fetching 16-11-2009 → 22-11-2009
Rows: 2
Fetching 23-11-2009 → 29-11-2009
Rows: 0
Fetching 30-11-2009 → 06-12-2009
Rows: 4
Fetching 07-12-2009 → 13-12-2009
Rows: 0
Fetching 14-12-2009 → 20-12-2009
Rows: 0
Fetching 21-12-2009 → 27-12-2009
Rows: 0
Fetching 28-12-2009 → 03-01-2010
Rows: 2
Fetching 04-01-2010 → 10-01-2010
Rows: 4
Fetching 11-01-2010 → 17-01-2010
Rows: 6
Fetching 18-01-2010 → 24-01-2010
Rows: 2
Fetching 25-01-2010 → 31-01-2010
Rows: 6
Fetching 01-02-2010 → 07-02-2010
Rows: 2
Fetching 08-02-2010 → 14-02-2010
Rows: 0
Fetching 15-02-2010 → 21-02-2010
Rows: 0
Fetching 22-02-2010 → 28-02-2010
Rows: 2
Fetching 01-03-2010 → 07-03-2010
Rows: 4
Fetching 08-03-2010 → 14-03-2010
Rows: 5
Fetching 15-03-2010 → 21-03-2010
Rows: 2
Fetching 22-03-2010 → 28-03-2010
Rows: 6
Fetching 29-03-2010 → 04-04-2010
Rows: 6
Fetching 05-04-2010 → 11-04-2010
Rows: 2
Fetching 12-04-2010 → 18-04-2010
Rows: 0
Fetching 19-04-2010 → 25-04-2010
Rows: 0
Fetching 26-04-2010 → 02-05-2010
Rows: 0

In [9]:
import pandas as pd
from nselib import capital_market
import os

SAVE_DIR = "/lakehouse/default/Files/data/raw/nse_block_hist"

from_dt = "02-10-2022"
to_dt = "03-10-2022"

print(f"Fetching {from_dt} → {to_dt}")

data = capital_market.block_deals_data(
    from_date=from_dt,
    to_date=to_dt
)

df = pd.DataFrame(data)

print(df.head())
print("Rows:", len(df))

file_path = os.path.join(
    SAVE_DIR,
    "missing_chunk_2022_10_03_to_2022_10_05.csv"
)

df.to_csv(file_path, index=False)

print("Saved:", file_path)

Fetching 02-10-2022 → 03-10-2022

ContentDecodingError: ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))

In [3]:
# correct version
import pandas as pd
from nselib import capital_market
from datetime import datetime


# Read trusted old file
df_old = pd.read_csv(
    "/lakehouse/default/Files/data/raw/nse_block_hist/blockdeals_23-03-2026.csv"
)

# Convert date column
df_old["Date"] = pd.to_datetime(
    df_old["Date"],
    dayfirst=True
)

# Find last trusted date
last_date = df_old["Date"].max()

print("Last date in old file:", last_date)

# Start next day
from_dt = (
    last_date + pd.Timedelta(days=1)
).strftime("%d-%m-%Y")

to_dt = datetime.today().strftime("%d-%m-%Y")

print(f"Fetching {from_dt} → {to_dt}")

# Fetch only missing period
data = capital_market.block_deals_data(
    from_date=from_dt,
    to_date=to_dt
)

df_new = pd.DataFrame(data)

print("New rows fetched:", len(df_new))

# Merge old + new
df_final = pd.concat(
    [df_old, df_new],
    ignore_index=True
)

# Remove duplicates
df_final = df_final.drop_duplicates()

print("Final rows:", len(df_final))

# Convert date back to readable format
df_final["Date"] = pd.to_datetime(
    df_final["Date"],
    dayfirst=True
).dt.strftime("%d-%m-%Y")

# Save final merged file
df_final.to_csv(
    "/lakehouse/default/Files/data/raw/nse_block_hist/blockdeals_31-05-2026.csv",
    index=False
)

print("Final historical file saved")

Last date in old file: 2026-03-19 00:00:00
Fetching 20-03-2026 → 01-06-2026
New rows fetched: 276
Final rows: 12286
Final historical file saved

## **NSE Bulk deals**

In [6]:
import pandas as pd
from nselib import capital_market

from_dt = "01-01-2026"
to_dt = "31-01-2026"

print(f"Fetching {from_dt} → {to_dt}")

data = capital_market.bulk_deal_data(
    from_date=from_dt,
    to_date=to_dt
)

df = pd.DataFrame(data)

print(df.head())
print("Rows:", len(df))

Fetching 01-01-2026 → 31-01-2026
          Date     Symbol              SecurityName  \
0  01-JAN-2026      AGIIL         Agi Infra Limited
1  01-JAN-2026      AGIIL         Agi Infra Limited
2  01-JAN-2026      AGIIL         Agi Infra Limited
3  01-JAN-2026      AGIIL         Agi Infra Limited
4  01-JAN-2026  FILATFASH  Filatex Fashions Limited

                        ClientName Buy/Sell QuantityTraded  \
0  ARIHANT CAPITAL MARKETS LIMITED      BUY       7,72,182
1  ARIHANT CAPITAL MARKETS LIMITED     SELL       8,26,930
2        ASTORNE CAPITAL VCC ARVEN      BUY      25,00,000
3             GIRIRAJ RATAN DAMANI     SELL       9,25,000
4      ACHINTYA SECURITIES LIMITED     SELL    4,05,04,754

  TradePrice/Wght.Avg.Price Remarks
0                    260.31       -
1                    260.84       -
2                    260.00       -
3                    260.00       -
4                      0.30       -
Rows: 1593

In [8]:
import pandas as pd
import os
from datetime import datetime, timedelta
from nselib import capital_market


SAVE_DIR = "/lakehouse/default/Files/data/raw/nse_bulk_hist"
os.makedirs(SAVE_DIR, exist_ok=True)

all_data = []

start_date = datetime(2001, 1, 1)
end_date = datetime.today()

current_start = start_date


while current_start <= end_date:

    current_end = current_start + timedelta(days=14)

    if current_end > end_date:
        current_end = end_date

    from_dt = current_start.strftime("%d-%m-%Y")
    to_dt = current_end.strftime("%d-%m-%Y")

    print(f"Fetching {from_dt} → {to_dt}")

    try:
        data = capital_market.bulk_deal_data(
            from_date=from_dt,
            to_date=to_dt
        )

        df_chunk = pd.DataFrame(data)

        print(f"Rows: {len(df_chunk)}")

        all_data.append(df_chunk)

    except Exception as e:
        print(f"ERROR -> {e}")

    current_start = current_end + timedelta(days=1)


# Combine all chunks
df = pd.concat(all_data, ignore_index=True)

print("Total rows:", len(df))

today = datetime.today().strftime("%d-%m-%Y")

file_name = f"bulkdeals_{today}.csv"

file_path = os.path.join(
    SAVE_DIR,
    file_name
)

df.to_csv(file_path, index=False)

print("Saved:", file_path)

Fetching 01-01-2001 → 15-01-2001
Rows: 0
Fetching 16-01-2001 → 30-01-2001
Rows: 0
Fetching 31-01-2001 → 14-02-2001
Rows: 0
Fetching 15-02-2001 → 01-03-2001
Rows: 0
Fetching 02-03-2001 → 16-03-2001
Rows: 0
Fetching 17-03-2001 → 31-03-2001
Rows: 0
Fetching 01-04-2001 → 15-04-2001
Rows: 0
Fetching 16-04-2001 → 30-04-2001
Rows: 0
Fetching 01-05-2001 → 15-05-2001
Rows: 0
Fetching 16-05-2001 → 30-05-2001
Rows: 0
Fetching 31-05-2001 → 14-06-2001
Rows: 0
Fetching 15-06-2001 → 29-06-2001
Rows: 0
Fetching 30-06-2001 → 14-07-2001
Rows: 0
Fetching 15-07-2001 → 29-07-2001
Rows: 0
Fetching 30-07-2001 → 13-08-2001
Rows: 0
Fetching 14-08-2001 → 28-08-2001
Rows: 0
Fetching 29-08-2001 → 12-09-2001
Rows: 0
Fetching 13-09-2001 → 27-09-2001
Rows: 0
Fetching 28-09-2001 → 12-10-2001
Rows: 0
Fetching 13-10-2001 → 27-10-2001
Rows: 0
Fetching 28-10-2001 → 11-11-2001
Rows: 0
Fetching 12-11-2001 → 26-11-2001
Rows: 0
Fetching 27-11-2001 → 11-12-2001
Rows: 0
Fetching 12-12-2001 → 26-12-2001
Rows: 0
Fetching 27-12-2001 → 10-01-2002
Rows: 0
Fetching 11-01-2002 → 25-01-2002
Rows: 0
Fetching 26-01-2002 → 09-02-2002
Rows: 0
Fetching 10-02-2002 → 24-02-2002
Rows: 0
Fetching 25-02-2002 → 11-03-2002
Rows: 0
Fetching 12-03-2002 → 26-03-2002
Rows: 0
Fetching 27-03-2002 → 10-04-2002
Rows: 0
Fetching 11-04-2002 → 25-04-2002
Rows: 0
Fetching 26-04-2002 → 10-05-2002
Rows: 0
Fetching 11-05-2002 → 25-05-2002
Rows: 0
Fetching 26-05-2002 → 09-06-2002
Rows: 0
Fetching 10-06-2002 → 24-06-2002
Rows: 0
Fetching 25-06-2002 → 09-07-2002
Rows: 0
Fetching 10-07-2002 → 24-07-2002
Rows: 0
Fetching 25-07-2002 → 08-08-2002
Rows: 0
Fetching 09-08-2002 → 23-08-2002
Rows: 0
Fetching 24-08-2002 → 07-09-2002
Rows: 0
Fetching 08-09-2002 → 22-09-2002
Rows: 0
Fetching 23-09-2002 → 07-10-2002
Rows: 0
Fetching 08-10-2002 → 22-10-2002
Rows: 0
Fetching 23-10-2002 → 06-11-2002
Rows: 0
Fetching 07-11-2002 → 21-11-2002
Rows: 0
Fetching 22-11-2002 → 06-12-2002
Rows: 0
Fetching 07-12-2002 → 21-12-2002
Rows: 0
Fetching 22-12-2002 → 05-01-2003
Rows: 0
Fetching 06-01-2003 → 20-01-2003
Rows: 0
Fetching 21-01-2003 → 04-02-2003
Rows: 0
Fetching 05-02-2003 → 19-02-2003
Rows: 0
Fetching 20-02-2003 → 06-03-2003
Rows: 0
Fetching 07-03-2003 → 21-03-2003
Rows: 0
Fetching 22-03-2003 → 05-04-2003
Rows: 0
Fetching 06-04-2003 → 20-04-2003
Rows: 0
Fetching 21-04-2003 → 05-05-2003
Rows: 0
Fetching 06-05-2003 → 20-05-2003
Rows: 0
Fetching 21-05-2003 → 04-06-2003
Rows: 0
Fetching 05-06-2003 → 19-06-2003
Rows: 0
Fetching 20-06-2003 → 04-07-2003
Rows: 0
Fetching 05-07-2003 → 19-07-2003
Rows: 0
Fetching 20-07-2003 → 03-08-2003
Rows: 0
Fetching 04-08-2003 → 18-08-2003
Rows: 0
Fetching 19-08-2003 → 02-09-2003
Rows: 0
Fetching 03-09-2003 → 17-09-2003
Rows: 0
Fetching 18-09-2003 → 02-10-2003
Rows: 0
Fetching 03-10-2003 → 17-10-2003
Rows: 0
Fetching 18-10-2003 → 01-11-2003
Rows: 0
Fetching 02-11-2003 → 16-11-2003
Rows: 0
Fetching 17-11-2003 → 01-12-2003
Rows: 0
Fetching 02-12-2003 → 16-12-2003
Rows: 0
Fetching 17-12-2003 → 31-12-2003
Rows: 0
Fetching 01-01-2004 → 15-01-2004
Rows: 32
Fetching 16-01-2004 → 30-01-2004
Rows: 0
Fetching 31-01-2004 → 14-02-2004
Rows: 0
Fetching 15-02-2004 → 29-02-2004
Rows: 24
Fetching 01-03-2004 → 15-03-2004
Rows: 31
Fetching 16-03-2004 → 30-03-2004
Rows: 46
Fetching 31-03-2004 → 14-04-2004
Rows: 29
Fetching 15-04-2004 → 29-04-2004
Rows: 35
Fetching 30-04-2004 → 14-05-2004
Rows: 30
Fetching 15-05-2004 → 29-05-2004
Rows: 17
Fetching 30-05-2004 → 13-06-2004
Rows: 28
Fetching 14-06-2004 → 28-06-2004
Rows: 16
Fetching 29-06-2004 → 13-07-2004
Rows: 38
Fetching 14-07-2004 → 28-07-2004
Rows: 35
Fetching 29-07-2004 → 12-08-2004
Rows: 37
Fetching 13-08-2004 → 27-08-2004
Rows: 52
Fetching 28-08-2004 → 11-09-2004
Rows: 73
Fetching 12-09-2004 → 26-09-2004
Rows: 59
Fetching 27-09-2004 → 11-10-2004
Rows: 100
Fetching 12-10-2004 → 26-10-2004
Rows: 57
Fetching 27-10-2004 → 10-11-2004
Rows: 105
Fetching 11-11-2004 → 25-11-2004
Rows: 84
Fetching 26-11-2004 → 10-12-2004
Rows: 83
Fetching 11-12-2004 → 25-12-2004
Rows: 89
Fetching 26-12-2004 → 09-01-2005
Rows: 115
Fetching 10-01-2005 → 24-01-2005
Rows: 51
Fetching 25-01-2005 → 08-02-2005
Rows: 113
Fetching 09-02-2005 → 23-02-2005
Rows: 126
Fetching 24-02-2005 → 10-03-2005
Rows: 177
Fetching 11-03-2005 → 25-03-2005
Rows: 85
Fetching 26-03-2005 → 09-04-2005
Rows: 78
Fetching 10-04-2005 → 24-04-2005
Rows: 81
Fetching 25-04-2005 → 09-05-2005
Rows: 129
Fetching 10-05-2005 → 24-05-2005
Rows: 237
Fetching 25-05-2005 → 08-06-2005
Rows: 195
Fetching 09-06-2005 → 23-06-2005
Rows: 230
Fetching 24-06-2005 → 08-07-2005
Rows: 190
Fetching 09-07-2005 → 23-07-2005
Rows: 303
Fetching 24-07-2005 → 07-08-2005
Rows: 234
Fetching 08-08-2005 → 22-08-2005
Rows: 503
Fetching 23-08-2005 → 06-09-2005
Rows: 650
Fetching 07-09-2005 → 21-09-2005
Rows: 766
Fetching 22-09-2005 → 06-10-2005
Rows: 554
Fetching 07-10-2005 → 21-10-2005
Rows: 285
Fetching 22-10-2005 → 05-11-2005
Rows: 138
Fetching 06-11-2005 → 20-11-2005
Rows: 326
Fetching 21-11-2005 → 05-12-2005
Rows: 477
Fetching 06-12-2005 → 20-12-2005
Rows: 440
Fetching 21-12-2005 → 04-01-2006
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 05-01-2006 → 19-01-2006
Rows: 638
Fetching 20-01-2006 → 03-02-2006
Rows: 638
Fetching 04-02-2006 → 18-02-2006
Rows: 473
Fetching 19-02-2006 → 05-03-2006
Rows: 549
Fetching 06-03-2006 → 20-03-2006
Rows: 527
Fetching 21-03-2006 → 04-04-2006
Rows: 593
Fetching 05-04-2006 → 19-04-2006
Rows: 273
Fetching 20-04-2006 → 04-05-2006
Rows: 327
Fetching 05-05-2006 → 19-05-2006
Rows: 388
Fetching 20-05-2006 → 03-06-2006
Rows: 77
Fetching 04-06-2006 → 18-06-2006
Rows: 89
Fetching 19-06-2006 → 03-07-2006
Rows: 107
Fetching 04-07-2006 → 18-07-2006
Rows: 37
Fetching 19-07-2006 → 02-08-2006
Rows: 48
Fetching 03-08-2006 → 17-08-2006
Rows: 97
Fetching 18-08-2006 → 01-09-2006
Rows: 143
Fetching 02-09-2006 → 16-09-2006
Rows: 173
Fetching 17-09-2006 → 01-10-2006
Rows: 392
Fetching 02-10-2006 → 16-10-2006
Rows: 496
Fetching 17-10-2006 → 31-10-2006
Rows: 258
Fetching 01-11-2006 → 15-11-2006
Rows: 470
Fetching 16-11-2006 → 30-11-2006
Rows: 386
Fetching 01-12-2006 → 15-12-2006
Rows: 359
Fetching 16-12-2006 → 30-12-2006
Rows: 524
Fetching 31-12-2006 → 14-01-2007
Rows: 638
Fetching 15-01-2007 → 29-01-2007
Rows: 386
Fetching 30-01-2007 → 13-02-2007
Rows: 1216
Fetching 14-02-2007 → 28-02-2007
Rows: 530
Fetching 01-03-2007 → 15-03-2007
Rows: 523
Fetching 16-03-2007 → 30-03-2007
Rows: 481
Fetching 31-03-2007 → 14-04-2007
Rows: 339
Fetching 15-04-2007 → 29-04-2007
Rows: 384
Fetching 30-04-2007 → 14-05-2007
Rows: 331
Fetching 15-05-2007 → 29-05-2007
Rows: 476
Fetching 30-05-2007 → 13-06-2007
Rows: 690
Fetching 14-06-2007 → 28-06-2007
Rows: 474
Fetching 29-06-2007 → 13-07-2007
Rows: 534
Fetching 14-07-2007 → 28-07-2007
Rows: 316
Fetching 29-07-2007 → 12-08-2007
Rows: 455
Fetching 13-08-2007 → 27-08-2007
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 28-08-2007 → 11-09-2007
Rows: 422
Fetching 12-09-2007 → 26-09-2007
Rows: 511
Fetching 27-09-2007 → 11-10-2007
Rows: 292
Fetching 12-10-2007 → 26-10-2007
Rows: 278
Fetching 27-10-2007 → 10-11-2007
Rows: 163
Fetching 11-11-2007 → 25-11-2007
Rows: 298
Fetching 26-11-2007 → 10-12-2007
Rows: 337
Fetching 11-12-2007 → 25-12-2007
Rows: 483
Fetching 26-12-2007 → 09-01-2008
Rows: 754
Fetching 10-01-2008 → 24-01-2008
Rows: 440
Fetching 25-01-2008 → 08-02-2008
Rows: 155
Fetching 09-02-2008 → 23-02-2008
Rows: 361
Fetching 24-02-2008 → 09-03-2008
Rows: 589
Fetching 10-03-2008 → 24-03-2008
Rows: 454
Fetching 25-03-2008 → 08-04-2008
Rows: 554
Fetching 09-04-2008 → 23-04-2008
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 24-04-2008 → 08-05-2008
Rows: 233
Fetching 09-05-2008 → 23-05-2008
Rows: 130
Fetching 24-05-2008 → 07-06-2008
Rows: 322
Fetching 08-06-2008 → 22-06-2008
Rows: 158
Fetching 23-06-2008 → 07-07-2008
Rows: 323
Fetching 08-07-2008 → 22-07-2008
Rows: 423
Fetching 23-07-2008 → 06-08-2008
Rows: 265
Fetching 07-08-2008 → 21-08-2008
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 22-08-2008 → 05-09-2008
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 06-09-2008 → 20-09-2008
Rows: 353
Fetching 21-09-2008 → 05-10-2008
Rows: 122
Fetching 06-10-2008 → 20-10-2008
Rows: 268
Fetching 21-10-2008 → 04-11-2008
Rows: 103
Fetching 05-11-2008 → 19-11-2008
Rows: 219
Fetching 20-11-2008 → 04-12-2008
Rows: 95
Fetching 05-12-2008 → 19-12-2008
Rows: 144
Fetching 20-12-2008 → 03-01-2009
Rows: 109
Fetching 04-01-2009 → 18-01-2009
Rows: 132
Fetching 19-01-2009 → 02-02-2009
Rows: 137
Fetching 03-02-2009 → 17-02-2009
Rows: 276
Fetching 18-02-2009 → 04-03-2009
Rows: 291
Fetching 05-03-2009 → 19-03-2009
Rows: 391
Fetching 20-03-2009 → 03-04-2009
Rows: 298
Fetching 04-04-2009 → 18-04-2009
Rows: 300
Fetching 19-04-2009 → 03-05-2009
Rows: 215
Fetching 04-05-2009 → 18-05-2009
Rows: 290
Fetching 19-05-2009 → 02-06-2009
Rows: 504
Fetching 03-06-2009 → 17-06-2009
Rows: 402
Fetching 18-06-2009 → 02-07-2009
Rows: 308
Fetching 03-07-2009 → 17-07-2009
Rows: 218
Fetching 18-07-2009 → 01-08-2009
Rows: 198
Fetching 02-08-2009 → 16-08-2009
Rows: 310
Fetching 17-08-2009 → 31-08-2009
Rows: 354
Fetching 01-09-2009 → 15-09-2009
Rows: 391
Fetching 16-09-2009 → 30-09-2009
Rows: 453
Fetching 01-10-2009 → 15-10-2009
Rows: 326
Fetching 16-10-2009 → 30-10-2009
Rows: 676
Fetching 31-10-2009 → 14-11-2009
Rows: 326
Fetching 15-11-2009 → 29-11-2009
Rows: 352
Fetching 30-11-2009 → 14-12-2009
Rows: 495
Fetching 15-12-2009 → 29-12-2009
Rows: 415
Fetching 30-12-2009 → 13-01-2010
Rows: 650
Fetching 14-01-2010 → 28-01-2010
Rows: 389
Fetching 29-01-2010 → 12-02-2010
Rows: 472
Fetching 13-02-2010 → 27-02-2010
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 28-02-2010 → 14-03-2010
Rows: 773
Fetching 15-03-2010 → 29-03-2010
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 30-03-2010 → 13-04-2010
Rows: 737
Fetching 14-04-2010 → 28-04-2010
Rows: 501
Fetching 29-04-2010 → 13-05-2010
Rows: 492
Fetching 14-05-2010 → 28-05-2010
Rows: 493
Fetching 29-05-2010 → 12-06-2010
Rows: 126
Fetching 13-06-2010 → 27-06-2010
Rows: 243
Fetching 28-06-2010 → 12-07-2010
Rows: 333
Fetching 13-07-2010 → 27-07-2010
Rows: 562
Fetching 28-07-2010 → 11-08-2010
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 12-08-2010 → 26-08-2010
Rows: 581
Fetching 27-08-2010 → 10-09-2010
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 11-09-2010 → 25-09-2010
Rows: 797
Fetching 26-09-2010 → 10-10-2010
Rows: 901
Fetching 11-10-2010 → 25-10-2010
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 26-10-2010 → 09-11-2010
Rows: 1075
Fetching 10-11-2010 → 24-11-2010
Rows: 807
Fetching 25-11-2010 → 09-12-2010
Rows: 438
Fetching 10-12-2010 → 24-12-2010
Rows: 383
Fetching 25-12-2010 → 08-01-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 09-01-2011 → 23-01-2011
Rows: 614
Fetching 24-01-2011 → 07-02-2011
Rows: 322
Fetching 08-02-2011 → 22-02-2011
Rows: 324
Fetching 23-02-2011 → 09-03-2011
Rows: 254
Fetching 10-03-2011 → 24-03-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 25-03-2011 → 08-04-2011
Rows: 607
Fetching 09-04-2011 → 23-04-2011
Rows: 159
Fetching 24-04-2011 → 08-05-2011
Rows: 280
Fetching 09-05-2011 → 23-05-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 24-05-2011 → 07-06-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 08-06-2011 → 22-06-2011
Rows: 546
Fetching 23-06-2011 → 07-07-2011
Rows: 740
Fetching 08-07-2011 → 22-07-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 23-07-2011 → 06-08-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 07-08-2011 → 21-08-2011
Rows: 362
Fetching 22-08-2011 → 05-09-2011
Rows: 443
Fetching 06-09-2011 → 20-09-2011
Rows: 526
Fetching 21-09-2011 → 05-10-2011
Rows: 595
Fetching 06-10-2011 → 20-10-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 21-10-2011 → 04-11-2011
ERROR -> ('Received response with content-encoding: br, but failed to decode it.', error("brotli: decoder process called with data when 'can_accept_more_data()' is False"))
Fetching 05-11-2011 → 19-11-2011
Rows: 278
Fetching 20-11-2011 → 04-12-2011
Rows: 143
Fetching 05-12-2011 → 19-12-2011
Rows: 153
Fetching 20-12-2011 → 03-01-2012
Rows: 136
Fetching 04-01-2012 → 18-01-2012
Rows: 243
Fetching 19-01-2012 → 02-02-2012
Rows: 181
Fetching 03-02-2012 → 17-02-2012
Rows: 188
Fetching 18-02-2012 → 03-03-2012
Rows: 162
Fetching 04-03-2012 → 18-03-2012
Rows: 226
Fetching 19-03-2012 → 02-04-2012
Rows: 347
Fetching 03-04-2012 → 17-04-2012
Rows: 169
Fetching 18-04-2012 → 02-05-2012
Rows: 114
Fetching 03-05-2012 → 17-05-2012
Rows: 95
Fetching 18-05-2012 → 01-06-2012
Rows: 141
Fetching 02-06-2012 → 16-06-2012
Rows: 103
Fetching 17-06-2012 → 01-07-2012
Rows: 150
Fetching 02-07-2012 → 16-07-2012
Rows: 366
Fetching 17-07-2012 → 31-07-2012
Rows: 173
Fetching 01-08-2012 → 15-08-2012
Rows: 99
Fetching 16-08-2012 → 30-08-2012
Rows: 211
Fetching 31-08-2012 → 14-09-2012
Rows: 242
Fetching 15-09-2012 → 29-09-2012
Rows: 286
Fetching 30-09-2012 → 14-10-2012
Rows: 195
Fetching 15-10-2012 → 29-10-2012
Rows: 191
Fetching 30-10-2012 → 13-11-2012
Rows: 211
Fetching 14-11-2012 → 28-11-2012
Rows: 211
Fetching 29-11-2012 → 13-12-2012
Rows: 324
Fetching 14-12-2012 → 28-12-2012
Rows: 225
Fetching 29-12-2012 → 12-01-2013
Rows: 174
Fetching 13-01-2013 → 27-01-2013
Rows: 163
Fetching 28-01-2013 → 11-02-2013
Rows: 145
Fetching 12-02-2013 → 26-02-2013
Rows: 174
Fetching 27-02-2013 → 13-03-2013
Rows: 133
Fetching 14-03-2013 → 28-03-2013
Rows: 165
Fetching 29-03-2013 → 12-04-2013
Rows: 105
Fetching 13-04-2013 → 27-04-2013
Rows: 112
Fetching 28-04-2013 → 12-05-2013
Rows: 76
Fetching 13-05-2013 → 27-05-2013
Rows: 111
Fetching 28-05-2013 → 11-06-2013
Rows: 117
Fetching 12-06-2013 → 26-06-2013
Rows: 105
Fetching 27-06-2013 → 11-07-2013
Rows: 86
Fetching 12-07-2013 → 26-07-2013
Rows: 90
Fetching 27-07-2013 → 10-08-2013
Rows: 182
Fetching 11-08-2013 → 25-08-2013
Rows: 130
Fetching 26-08-2013 → 09-09-2013
Rows: 111
Fetching 10-09-2013 → 24-09-2013
Rows: 193
Fetching 25-09-2013 → 09-10-2013
Rows: 73
Fetching 10-10-2013 → 24-10-2013
Rows: 48
Fetching 25-10-2013 → 08-11-2013
Rows: 67
Fetching 09-11-2013 → 23-11-2013
Rows: 69
Fetching 24-11-2013 → 08-12-2013
Rows: 134
Fetching 09-12-2013 → 23-12-2013
Rows: 93
Fetching 24-12-2013 → 07-01-2014
Rows: 109
Fetching 08-01-2014 → 22-01-2014
Rows: 125
Fetching 23-01-2014 → 06-02-2014
Rows: 124
Fetching 07-02-2014 → 21-02-2014
Rows: 68
Fetching 22-02-2014 → 08-03-2014
Rows: 105
Fetching 09-03-2014 → 23-03-2014
Rows: 100
Fetching 24-03-2014 → 07-04-2014
Rows: 187
Fetching 08-04-2014 → 22-04-2014
Rows: 109
Fetching 23-04-2014 → 07-05-2014
Rows: 118
Fetching 08-05-2014 → 22-05-2014
Rows: 207
Fetching 23-05-2014 → 06-06-2014
Rows: 182
Fetching 07-06-2014 → 21-06-2014
Rows: 236
Fetching 22-06-2014 → 06-07-2014
Rows: 200
Fetching 07-07-2014 → 21-07-2014
Rows: 222
Fetching 22-07-2014 → 05-08-2014
Rows: 182
Fetching 06-08-2014 → 20-08-2014
Rows: 167
Fetching 21-08-2014 → 04-09-2014
Rows: 179
Fetching 05-09-2014 → 19-09-2014
Rows: 379
Fetching 20-09-2014 → 04-10-2014
Rows: 127
Fetching 05-10-2014 → 19-10-2014
Rows: 95
Fetching 20-10-2014 → 03-11-2014
Rows: 175
Fetching 04-11-2014 → 18-11-2014
Rows: 164
Fetching 19-11-2014 → 03-12-2014
Rows: 197
Fetching 04-12-2014 → 18-12-2014
Rows: 143
Fetching 19-12-2014 → 02-01-2015
Rows: 123
Fetching 03-01-2015 → 17-01-2015
Rows: 152
Fetching 18-01-2015 → 01-02-2015
Rows: 147
Fetching 02-02-2015 → 16-02-2015
Rows: 94
Fetching 17-02-2015 → 03-03-2015
Rows: 306
Fetching 04-03-2015 → 18-03-2015
Rows: 212
Fetching 19-03-2015 → 02-04-2015
Rows: 171
Fetching 03-04-2015 → 17-04-2015
Rows: 150
Fetching 18-04-2015 → 02-05-2015
Rows: 107
Fetching 03-05-2015 → 17-05-2015
Rows: 123
Fetching 18-05-2015 → 01-06-2015
Rows: 130
Fetching 02-06-2015 → 16-06-2015
Rows: 166
Fetching 17-06-2015 → 01-07-2015
Rows: 199
Fetching 02-07-2015 → 16-07-2015
Rows: 250
Fetching 17-07-2015 → 31-07-2015
Rows: 177
Fetching 01-08-2015 → 15-08-2015
Rows: 178
Fetching 16-08-2015 → 30-08-2015
Rows: 159
Fetching 31-08-2015 → 14-09-2015
Rows: 179
Fetching 15-09-2015 → 29-09-2015
Rows: 177
Fetching 30-09-2015 → 14-10-2015
Rows: 168
Fetching 15-10-2015 → 29-10-2015
Rows: 152
Fetching 30-10-2015 → 13-11-2015
Rows: 112
Fetching 14-11-2015 → 28-11-2015
Rows: 189
Fetching 29-11-2015 → 13-12-2015
Rows: 269
Fetching 14-12-2015 → 28-12-2015
Rows: 262
Fetching 29-12-2015 → 12-01-2016
Rows: 366
Fetching 13-01-2016 → 27-01-2016
Rows: 173
Fetching 28-01-2016 → 11-02-2016
Rows: 178
Fetching 12-02-2016 → 26-02-2016
Rows: 181
Fetching 27-02-2016 → 12-03-2016
Rows: 155
Fetching 13-03-2016 → 27-03-2016
Rows: 213
Fetching 28-03-2016 → 11-04-2016
Rows: 291
Fetching 12-04-2016 → 26-04-2016
Rows: 171
Fetching 27-04-2016 → 11-05-2016
Rows: 206
Fetching 12-05-2016 → 26-05-2016
Rows: 171
Fetching 27-05-2016 → 10-06-2016
Rows: 221
Fetching 11-06-2016 → 25-06-2016
Rows: 291
Fetching 26-06-2016 → 10-07-2016
Rows: 322
Fetching 11-07-2016 → 25-07-2016
Rows: 387
Fetching 26-07-2016 → 09-08-2016
Rows: 288
Fetching 10-08-2016 → 24-08-2016
Rows: 222
Fetching 25-08-2016 → 08-09-2016
Rows: 260
Fetching 09-09-2016 → 23-09-2016
Rows: 270
Fetching 24-09-2016 → 08-10-2016
Rows: 344
Fetching 09-10-2016 → 23-10-2016
Rows: 382
Fetching 24-10-2016 → 07-11-2016
Rows: 451
Fetching 08-11-2016 → 22-11-2016
Rows: 173
Fetching 23-11-2016 → 07-12-2016
Rows: 293
Fetching 08-12-2016 → 22-12-2016
Rows: 221
Fetching 23-12-2016 → 06-01-2017
Rows: 225
Fetching 07-01-2017 → 21-01-2017
Rows: 398
Fetching 22-01-2017 → 05-02-2017
Rows: 142
Fetching 06-02-2017 → 20-02-2017
Rows: 296
Fetching 21-02-2017 → 07-03-2017
Rows: 310
Fetching 08-03-2017 → 22-03-2017
Rows: 406
Fetching 23-03-2017 → 06-04-2017
Rows: 731
Fetching 07-04-2017 → 21-04-2017
Rows: 487
Fetching 22-04-2017 → 06-05-2017
Rows: 301
Fetching 07-05-2017 → 21-05-2017
Rows: 275
Fetching 22-05-2017 → 05-06-2017
Rows: 287
Fetching 06-06-2017 → 20-06-2017
Rows: 298

In [15]:
# correct version
import pandas as pd
import requests
import io
import os
import time
from datetime import datetime
from calendar import monthrange


SAVE_DIR = "/lakehouse/default/Files/data/raw/nse_bulk_hist"
os.makedirs(SAVE_DIR, exist_ok=True)

session = requests.Session()

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/csv,*/*",
    "Accept-Encoding": "gzip, deflate",   # disable brotli
    "Referer": "https://www.nseindia.com/"
}

# Get cookies
session.get(
    "https://www.nseindia.com",
    headers=headers
)

all_data = []

current_year = datetime.today().year
current_month = datetime.today().month


for year in range(2001, current_year + 1):

    print(f"\nProcessing {year}")

    for month in range(1, 13):

        if year == current_year and month > current_month:
            break

        from_dt = f"01-{month:02d}-{year}"

        last_day = monthrange(year, month)[1]

        to_dt = f"{last_day:02d}-{month:02d}-{year}"

        if year == current_year and month == current_month:
            to_dt = datetime.today().strftime("%d-%m-%Y")

        print(f"Fetching {from_dt} → {to_dt}")

        try:

            url = (
                "https://www.nseindia.com/api/"
                "historicalOR/bulk-block-short-deals"
                f"?optionType=bulk_deals"
                f"&from={from_dt}"
                f"&to={to_dt}"
                f"&csv=true"
            )

            response = session.get(
                url,
                headers=headers,
                timeout=30
            )

            if response.status_code != 200:
                print(f"Failed: {response.status_code}")
                continue

            df_month = pd.read_csv(
                io.StringIO(response.text)
            )

            # clean weird column names
            df_month.columns = (
                df_month.columns
                .str.replace("ï»¿", "", regex=False)
                .str.strip()
            )

            print(f"Rows: {len(df_month)}")

            if not df_month.empty:
                all_data.append(df_month)

            time.sleep(0.5)

        except Exception as e:
            print(f"ERROR -> {e}")


# Combine all months
df_final = pd.concat(
    all_data,
    ignore_index=True
)

# Remove duplicates
df_final = df_final.drop_duplicates()

print("Final rows:", len(df_final))

today = datetime.today().strftime("%d-%m-%Y")

file_path = os.path.join(
    SAVE_DIR,
    f"bulkdeals_{today}.csv"
)

df_final.to_csv(
    file_path,
    index=False
)

print("Saved:", file_path)

Processing 2001
Fetching 01-01-2001 → 31-01-2001
Rows: 0
Fetching 01-02-2001 → 28-02-2001
Rows: 0
Fetching 01-03-2001 → 31-03-2001
Rows: 0
Fetching 01-04-2001 → 30-04-2001
Rows: 0
Fetching 01-05-2001 → 31-05-2001
Rows: 0
Fetching 01-06-2001 → 30-06-2001
Rows: 0
Fetching 01-07-2001 → 31-07-2001
Rows: 0
Fetching 01-08-2001 → 31-08-2001
Rows: 0
Fetching 01-09-2001 → 30-09-2001
Rows: 0
Fetching 01-10-2001 → 31-10-2001
Rows: 0
Fetching 01-11-2001 → 30-11-2001
Rows: 0
Fetching 01-12-2001 → 31-12-2001
Rows: 0

Processing 2002
Fetching 01-01-2002 → 31-01-2002
Rows: 0
Fetching 01-02-2002 → 28-02-2002
Rows: 0
Fetching 01-03-2002 → 31-03-2002
Rows: 0
Fetching 01-04-2002 → 30-04-2002
Rows: 0
Fetching 01-05-2002 → 31-05-2002
Rows: 0
Fetching 01-06-2002 → 30-06-2002
Rows: 0
Fetching 01-07-2002 → 31-07-2002
Rows: 0
Fetching 01-08-2002 → 31-08-2002
Rows: 0
Fetching 01-09-2002 → 30-09-2002
Rows: 0
Fetching 01-10-2002 → 31-10-2002
Rows: 0
Fetching 01-11-2002 → 30-11-2002
Rows: 0
Fetching 01-12-2002 → 31-12-2002
Rows: 0

Processing 2003
Fetching 01-01-2003 → 31-01-2003
Rows: 0
Fetching 01-02-2003 → 28-02-2003
Rows: 0
Fetching 01-03-2003 → 31-03-2003
Rows: 0
Fetching 01-04-2003 → 30-04-2003
Rows: 0
Fetching 01-05-2003 → 31-05-2003
Rows: 0
Fetching 01-06-2003 → 30-06-2003
Rows: 0
Fetching 01-07-2003 → 31-07-2003
Rows: 0
Fetching 01-08-2003 → 31-08-2003
Rows: 0
Fetching 01-09-2003 → 30-09-2003
Rows: 0
Fetching 01-10-2003 → 31-10-2003
Rows: 0
Fetching 01-11-2003 → 30-11-2003
Rows: 0
Fetching 01-12-2003 → 31-12-2003
Rows: 0

Processing 2004
Fetching 01-01-2004 → 31-01-2004
Rows: 32
Fetching 01-02-2004 → 29-02-2004
Rows: 24
Fetching 01-03-2004 → 31-03-2004
Rows: 79
Fetching 01-04-2004 → 30-04-2004
Rows: 66
Fetching 01-05-2004 → 31-05-2004
Rows: 49
Fetching 01-06-2004 → 30-06-2004
Rows: 47
Fetching 01-07-2004 → 31-07-2004
Rows: 70
Fetching 01-08-2004 → 31-08-2004
Rows: 103
Fetching 01-09-2004 → 30-09-2004
Rows: 142
Fetching 01-10-2004 → 31-10-2004
Rows: 148
Fetching 01-11-2004 → 30-11-2004
Rows: 186
Fetching 01-12-2004 → 31-12-2004
Rows: 207

Processing 2005
Fetching 01-01-2005 → 31-01-2005
Rows: 149
Fetching 01-02-2005 → 28-02-2005
Rows: 244
Fetching 01-03-2005 → 31-03-2005
Rows: 250
Fetching 01-04-2005 → 30-04-2005
Rows: 199
Fetching 01-05-2005 → 31-05-2005
Rows: 370
Fetching 01-06-2005 → 30-06-2005
Rows: 450
Fetching 01-07-2005 → 31-07-2005
Rows: 481
Fetching 01-08-2005 → 31-08-2005
Rows: 966
Fetching 01-09-2005 → 30-09-2005
Rows: 1540
Fetching 01-10-2005 → 31-10-2005
Rows: 536
Fetching 01-11-2005 → 30-11-2005
Rows: 690
Fetching 01-12-2005 → 31-12-2005
Rows: 1043

Processing 2006
Fetching 01-01-2006 → 31-01-2006
Rows: 1354
Fetching 01-02-2006 → 28-02-2006
Rows: 827
Fetching 01-03-2006 → 31-03-2006
Rows: 1361
Fetching 01-04-2006 → 30-04-2006
Rows: 615
Fetching 01-05-2006 → 31-05-2006
Rows: 489
Fetching 01-06-2006 → 30-06-2006
Rows: 208
Fetching 01-07-2006 → 31-07-2006
Rows: 83
Fetching 01-08-2006 → 31-08-2006
Rows: 247
Fetching 01-09-2006 → 30-09-2006
Rows: 567
Fetching 01-10-2006 → 31-10-2006
Rows: 754
Fetching 01-11-2006 → 30-11-2006
Rows: 856
Fetching 01-12-2006 → 31-12-2006
Rows: 883

Processing 2007
Fetching 01-01-2007 → 31-01-2007
Rows: 1128
Fetching 01-02-2007 → 28-02-2007
Rows: 1642
Fetching 01-03-2007 → 31-03-2007
Rows: 1004
Fetching 01-04-2007 → 30-04-2007
Rows: 730
Fetching 01-05-2007 → 31-05-2007
Rows: 991
Fetching 01-06-2007 → 30-06-2007
Rows: 1009
Fetching 01-07-2007 → 31-07-2007
Rows: 863
Fetching 01-08-2007 → 31-08-2007
Rows: 1328
Fetching 01-09-2007 → 30-09-2007
Rows: 870
Fetching 01-10-2007 → 31-10-2007
Rows: 565
Fetching 01-11-2007 → 30-11-2007
Rows: 530
Fetching 01-12-2007 → 31-12-2007
Rows: 925

Processing 2008
Fetching 01-01-2008 → 31-01-2008
Rows: 1023
Fetching 01-02-2008 → 29-02-2008
Rows: 879
Fetching 01-03-2008 → 31-03-2008
Rows: 794
Fetching 01-04-2008 → 30-04-2008
Rows: 1163
Fetching 01-05-2008 → 31-05-2008
Rows: 380
Fetching 01-06-2008 → 30-06-2008
Rows: 479
Fetching 01-07-2008 → 31-07-2008
Rows: 750
Fetching 01-08-2008 → 31-08-2008
Rows: 2049
Fetching 01-09-2008 → 30-09-2008
Rows: 967
Fetching 01-10-2008 → 31-10-2008
Rows: 359
Fetching 01-11-2008 → 30-11-2008
Rows: 305
Fetching 01-12-2008 → 31-12-2008
Rows: 250

Processing 2009
Fetching 01-01-2009 → 31-01-2009
Rows: 297
Fetching 01-02-2009 → 28-02-2009
Rows: 378
Fetching 01-03-2009 → 31-03-2009
Rows: 845
Fetching 01-04-2009 → 30-04-2009
Rows: 557
Fetching 01-05-2009 → 31-05-2009
Rows: 691
Fetching 01-06-2009 → 30-06-2009
Rows: 744
Fetching 01-07-2009 → 31-07-2009
Rows: 485
Fetching 01-08-2009 → 31-08-2009
Rows: 664
Fetching 01-09-2009 → 30-09-2009
Rows: 844
Fetching 01-10-2009 → 31-10-2009
Rows: 1002
Fetching 01-11-2009 → 30-11-2009
Rows: 709
Fetching 01-12-2009 → 31-12-2009
Rows: 1004

Processing 2010
Fetching 01-01-2010 → 31-01-2010
Rows: 935
Fetching 01-02-2010 → 28-02-2010
Rows: 1350
Fetching 01-03-2010 → 31-03-2010
Rows: 1835
Fetching 01-04-2010 → 30-04-2010
Rows: 1201
Fetching 01-05-2010 → 31-05-2010
Rows: 908
Fetching 01-06-2010 → 30-06-2010
Rows: 434
Fetching 01-07-2010 → 31-07-2010
Rows: 1402
Fetching 01-08-2010 → 31-08-2010
Rows: 1324
Fetching 01-09-2010 → 30-09-2010
Rows: 1634
Fetching 01-10-2010 → 31-10-2010
Rows: 2642
Fetching 01-11-2010 → 30-11-2010
Rows: 1427
Fetching 01-12-2010 → 31-12-2010
Rows: 1110

Processing 2011
Fetching 01-01-2011 → 31-01-2011
Rows: 1122
Fetching 01-02-2011 → 28-02-2011
Rows: 596
Fetching 01-03-2011 → 31-03-2011
Rows: 1258
Fetching 01-04-2011 → 30-04-2011
Rows: 659
Fetching 01-05-2011 → 31-05-2011
Rows: 1439
Fetching 01-06-2011 → 30-06-2011
Rows: 1228
Fetching 01-07-2011 → 31-07-2011
Rows: 1939
Fetching 01-08-2011 → 31-08-2011
Rows: 1053
Fetching 01-09-2011 → 30-09-2011
Rows: 1113
Fetching 01-10-2011 → 31-10-2011
Rows: 1363
Fetching 01-11-2011 → 30-11-2011
Rows: 710
Fetching 01-12-2011 → 31-12-2011
Rows: 288

Processing 2012
Fetching 01-01-2012 → 31-01-2012
Rows: 403
Fetching 01-02-2012 → 29-02-2012
Rows: 358
Fetching 01-03-2012 → 31-03-2012
Rows: 593
Fetching 01-04-2012 → 30-04-2012
Rows: 296
Fetching 01-05-2012 → 31-05-2012
Rows: 222
Fetching 01-06-2012 → 30-06-2012
Rows: 274
Fetching 01-07-2012 → 31-07-2012
Rows: 539
Fetching 01-08-2012 → 31-08-2012
Rows: 328
Fetching 01-09-2012 → 30-09-2012
Rows: 510
Fetching 01-10-2012 → 31-10-2012
Rows: 415
Fetching 01-11-2012 → 30-11-2012
Rows: 485
Fetching 01-12-2012 → 31-12-2012
Rows: 483

Processing 2013
Fetching 01-01-2013 → 31-01-2013
Rows: 373
Fetching 01-02-2013 → 28-02-2013
Rows: 302
Fetching 01-03-2013 → 31-03-2013
Rows: 253
Fetching 01-04-2013 → 30-04-2013
Rows: 239
Fetching 01-05-2013 → 31-05-2013
Rows: 216
Fetching 01-06-2013 → 30-06-2013
Rows: 188
Fetching 01-07-2013 → 31-07-2013
Rows: 182
Fetching 01-08-2013 → 31-08-2013
Rows: 358
Fetching 01-09-2013 → 30-09-2013
Rows: 268
Fetching 01-10-2013 → 31-10-2013
Rows: 126
Fetching 01-11-2013 → 30-11-2013
Rows: 140
Fetching 01-12-2013 → 31-12-2013
Rows: 230

Processing 2014
Fetching 01-01-2014 → 31-01-2014
Rows: 280
Fetching 01-02-2014 → 28-02-2014
Rows: 147
Fetching 01-03-2014 → 31-03-2014
Rows: 266
Fetching 01-04-2014 → 30-04-2014
Rows: 276
Fetching 01-05-2014 → 31-05-2014
Rows: 324
Fetching 01-06-2014 → 30-06-2014
Rows: 423
Fetching 01-07-2014 → 31-07-2014
Rows: 468
Fetching 01-08-2014 → 31-08-2014
Rows: 308
Fetching 01-09-2014 → 30-09-2014
Rows: 572
Fetching 01-10-2014 → 31-10-2014
Rows: 265
Fetching 01-11-2014 → 30-11-2014
Rows: 323
Fetching 01-12-2014 → 31-12-2014
Rows: 302

Processing 2015
Fetching 01-01-2015 → 31-01-2015
Rows: 323
Fetching 01-02-2015 → 28-02-2015
Rows: 338
Fetching 01-03-2015 → 31-03-2015
Rows: 435
Fetching 01-04-2015 → 30-04-2015
Rows: 267
Fetching 01-05-2015 → 31-05-2015
Rows: 241
Fetching 01-06-2015 → 30-06-2015
Rows: 367
Fetching 01-07-2015 → 31-07-2015
Rows: 437
Fetching 01-08-2015 → 31-08-2015
Rows: 359
Fetching 01-09-2015 → 30-09-2015
Rows: 342
Fetching 01-10-2015 → 31-10-2015
Rows: 322
Fetching 01-11-2015 → 30-11-2015
Rows: 336
Fetching 01-12-2015 → 31-12-2015
Rows: 594

Processing 2016
Fetching 01-01-2016 → 31-01-2016
Rows: 467
Fetching 01-02-2016 → 29-02-2016
Rows: 329
Fetching 01-03-2016 → 31-03-2016
Rows: 482
Fetching 01-04-2016 → 30-04-2016
Rows: 399
Fetching 01-05-2016 → 31-05-2016
Rows: 357
Fetching 01-06-2016 → 30-06-2016
Rows: 610
Fetching 01-07-2016 → 31-07-2016
Rows: 691
Fetching 01-08-2016 → 31-08-2016
Rows: 504
Fetching 01-09-2016 → 30-09-2016
Rows: 559
Fetching 01-10-2016 → 31-10-2016
Rows: 868
Fetching 01-11-2016 → 30-11-2016
Rows: 554
Fetching 01-12-2016 → 31-12-2016
Rows: 416

Processing 2017
Fetching 01-01-2017 → 31-01-2017
Rows: 580
Fetching 01-02-2017 → 28-02-2017
Rows: 552
Fetching 01-03-2017 → 31-03-2017
Rows: 1089
Fetching 01-04-2017 → 30-04-2017
Rows: 824
Fetching 01-05-2017 → 31-05-2017
Rows: 625
Fetching 01-06-2017 → 30-06-2017
Rows: 638
Fetching 01-07-2017 → 31-07-2017
Rows: 761
Fetching 01-08-2017 → 31-08-2017
Rows: 647
Fetching 01-09-2017 → 30-09-2017
Rows: 811
Fetching 01-10-2017 → 31-10-2017
Rows: 966
Fetching 01-11-2017 → 30-11-2017
Rows: 1403
Fetching 01-12-2017 → 31-12-2017
Rows: 1195

Processing 2018
Fetching 01-01-2018 → 31-01-2018
Rows: 1361
Fetching 01-02-2018 → 28-02-2018
Rows: 653
Fetching 01-03-2018 → 31-03-2018
Rows: 834
Fetching 01-04-2018 → 30-04-2018
Rows: 695
Fetching 01-05-2018 → 31-05-2018
Rows: 811
Fetching 01-06-2018 → 30-06-2018
Rows: 445
Fetching 01-07-2018 → 31-07-2018
Rows: 363
Fetching 01-08-2018 → 31-08-2018
Rows: 499
Fetching 01-09-2018 → 30-09-2018
Rows: 591
Fetching 01-10-2018 → 31-10-2018
Rows: 617
Fetching 01-11-2018 → 30-11-2018
Rows: 485
Fetching 01-12-2018 → 31-12-2018
Rows: 472

Processing 2019
Fetching 01-01-2019 → 31-01-2019
Rows: 532
Fetching 01-02-2019 → 28-02-2019
Rows: 724
Fetching 01-03-2019 → 31-03-2019
Rows: 813
Fetching 01-04-2019 → 30-04-2019
Rows: 588
Fetching 01-05-2019 → 31-05-2019
Rows: 651
Fetching 01-06-2019 → 30-06-2019
Rows: 1024
Fetching 01-07-2019 → 31-07-2019
Rows: 619
Fetching 01-08-2019 → 31-08-2019
Rows: 487
Fetching 01-09-2019 → 30-09-2019
Rows: 567
Fetching 01-10-2019 → 31-10-2019
Rows: 460
Fetching 01-11-2019 → 30-11-2019
Rows: 600
Fetching 01-12-2019 → 31-12-2019
Rows: 500

Processing 2020
Fetching 01-01-2020 → 31-01-2020
Rows: 614
Fetching 01-02-2020 → 29-02-2020
Rows: 373
Fetching 01-03-2020 → 31-03-2020
Rows: 609
Fetching 01-04-2020 → 30-04-2020
Rows: 412
Fetching 01-05-2020 → 31-05-2020
Rows: 377
Fetching 01-06-2020 → 30-06-2020
Rows: 923
Fetching 01-07-2020 → 31-07-2020
Rows: 605
Fetching 01-08-2020 → 31-08-2020
Rows: 621
Fetching 01-09-2020 → 30-09-2020
Rows: 478
Fetching 01-10-2020 → 31-10-2020
Rows: 352
Fetching 01-11-2020 → 30-11-2020
Rows: 599
Fetching 01-12-2020 → 31-12-2020
Rows: 1029

Processing 2021
Fetching 01-01-2021 → 31-01-2021
Rows: 778
Fetching 01-02-2021 → 28-02-2021
Rows: 740
Fetching 01-03-2021 → 31-03-2021
Rows: 868
Fetching 01-04-2021 → 30-04-2021
Rows: 524
Fetching 01-05-2021 → 31-05-2021
Rows: 1000
Fetching 01-06-2021 → 30-06-2021
Rows: 2171
Fetching 01-07-2021 → 31-07-2021
Rows: 1896
Fetching 01-08-2021 → 31-08-2021
Rows: 956
Fetching 01-09-2021 → 30-09-2021
Rows: 1037
Fetching 01-10-2021 → 31-10-2021
Rows: 913
Fetching 01-11-2021 → 30-11-2021
Rows: 666
Fetching 01-12-2021 → 31-12-2021
Rows: 1504

Processing 2022
Fetching 01-01-2022 → 31-01-2022
Rows: 1795
Fetching 01-02-2022 → 28-02-2022
Rows: 824
Fetching 01-03-2022 → 31-03-2022
Rows: 974
Fetching 01-04-2022 → 30-04-2022
Rows: 1166
Fetching 01-05-2022 → 31-05-2022
Rows: 543
Fetching 01-06-2022 → 30-06-2022
Rows: 701
Fetching 01-07-2022 → 31-07-2022
Rows: 576
Fetching 01-08-2022 → 31-08-2022
Rows: 892
Fetching 01-09-2022 → 30-09-2022
Rows: 1539
Fetching 01-10-2022 → 31-10-2022
Rows: 722
Fetching 01-11-2022 → 30-11-2022
Rows: 1035
Fetching 01-12-2022 → 31-12-2022
Rows: 1523

Processing 2023
Fetching 01-01-2023 → 31-01-2023
Rows: 1367
Fetching 01-02-2023 → 28-02-2023
Rows: 692
Fetching 01-03-2023 → 31-03-2023
Rows: 942
Fetching 01-04-2023 → 30-04-2023
Rows: 804
Fetching 01-05-2023 → 31-05-2023
Rows: 925
Fetching 01-06-2023 → 30-06-2023
Rows: 1472
Fetching 01-07-2023 → 31-07-2023
Rows: 1438
Fetching 01-08-2023 → 31-08-2023
Rows: 1919
Fetching 01-09-2023 → 30-09-2023
Rows: 1883
Fetching 01-10-2023 → 31-10-2023
Rows: 2079
Fetching 01-11-2023 → 30-11-2023
Rows: 1930
Fetching 01-12-2023 → 31-12-2023
Rows: 3079

Processing 2024
Fetching 01-01-2024 → 31-01-2024
Rows: 3908
Fetching 01-02-2024 → 29-02-2024
Rows: 2514
Fetching 01-03-2024 → 31-03-2024
Rows: 1197
Fetching 01-04-2024 → 30-04-2024
Rows: 1427
Fetching 01-05-2024 → 31-05-2024
Rows: 1307
Fetching 01-06-2024 → 30-06-2024
Rows: 2564
Fetching 01-07-2024 → 31-07-2024
Rows: 3080
Fetching 01-08-2024 → 31-08-2024
Rows: 3218
Fetching 01-09-2024 → 30-09-2024
Rows: 3117
Fetching 01-10-2024 → 31-10-2024
Rows: 1401
Fetching 01-11-2024 → 30-11-2024
Rows: 808
Fetching 01-12-2024 → 31-12-2024
Rows: 2144

Processing 2025
Fetching 01-01-2025 → 31-01-2025
Rows: 1472
Fetching 01-02-2025 → 28-02-2025
Rows: 890
Fetching 01-03-2025 → 31-03-2025
Rows: 1337
Fetching 01-04-2025 → 30-04-2025
Rows: 776
Fetching 01-05-2025 → 31-05-2025
Rows: 1127
Fetching 01-06-2025 → 30-06-2025
Rows: 1414
Fetching 01-07-2025 → 31-07-2025
Rows: 2122
Fetching 01-08-2025 → 31-08-2025
Rows: 1634
Fetching 01-09-2025 → 30-09-2025
Rows: 2648
Fetching 01-10-2025 → 31-10-2025
Rows: 1873
Fetching 01-11-2025 → 30-11-2025
Rows: 1686
Fetching 01-12-2025 → 31-12-2025
Rows: 2428

Processing 2026
Fetching 01-01-2026 → 31-01-2026
Rows: 1593
Fetching 01-02-2026 → 28-02-2026
Rows: 1577
Fetching 01-03-2026 → 31-03-2026
Rows: 2235
Fetching 01-04-2026 → 30-04-2026
Rows: 1944
Fetching 01-05-2026 → 31-05-2026
Rows: 1750
Fetching 01-06-2026 → 01-06-2026
Rows: 0
Final rows: 228356
Saved: /lakehouse/default/Files/data/raw/nse_bulk_hist/bulkdeals_01-06-2026.csv

In [18]:
import pandas as pd

df = pd.read_csv(
    "/lakehouse/default/Files/data/raw/nse_bulk_hist/bulkdeals_01-06-2026.csv"
)

df.columns = df.columns.str.strip()

print(df.columns.tolist())

['"Date "', 'Symbol', 'Security Name', 'Client Name', 'Buy / Sell', 'Quantity Traded', 'Trade Price / Wght. Avg. Price', 'Remarks']

In [20]:
import pandas as pd

file_path = "/lakehouse/default/Files/data/raw/nse_bulk_hist/bulkdeals_01-06-2026.csv"

df = pd.read_csv(file_path)

# clean headers
df.columns = (
    df.columns
    .str.replace('"', '', regex=False)
    .str.strip()
)

print("Rows:", len(df))

print("\nLast 10 rows:")
print(df.tail(10))

print("\nColumns:")
print(df.columns.tolist())

Rows: 228356

Last 10 rows:
               Date    Symbol              Security Name  \
228346  29-MAY-2026       TBZ     Trib Bhimji Zaveri Ltd
228347  29-MAY-2026       TBZ     Trib Bhimji Zaveri Ltd
228348  29-MAY-2026   TFCILTD       Tourism Finance Corp
228349  29-MAY-2026   TFCILTD       Tourism Finance Corp
228350  29-MAY-2026      TICL  Twamev Cons and Infra Ltd
228351  29-MAY-2026      TICL  Twamev Cons and Infra Ltd
228352  29-MAY-2026   VIVIDEL  Vivid Electromech Limited
228353  29-MAY-2026   VIVIDEL  Vivid Electromech Limited
228354  29-MAY-2026  VOLERCAR          Voler Car Limited
228355  29-MAY-2026  VOLERCAR          Voler Car Limited

                                          Client Name Buy / Sell  \
228346                        SETU SECURITIES PVT LTD        BUY
228347                        SETU SECURITIES PVT LTD       SELL
228348                    F3 ADVISORS PRIVATE LIMITED        BUY
228349                    F3 ADVISORS PRIVATE LIMITED       SELL
228350                                   SHILPI GUPTA       SELL
228351                                   SHILPI GUPTA        BUY
228352  MANSI SHARE AND STOCK BROKING PRIVATE LIMITED       SELL
228353                            SHAH GEETA   CHETAN        BUY
228354                  PROGNOSIS SECURITIES PVT. LTD       SELL
228355                  PROGNOSIS SECURITIES PVT. LTD        BUY

       Quantity Traded Trade Price / Wght. Avg. Price Remarks
228346        2,84,833                         164.82       -
228347        5,15,741                         165.47       -
228348       24,28,627                          73.08       -
228349       38,35,223                          73.27       -
228350          33,190                          23.08       -
228351        7,86,827                          23.04       -
228352          62,880                         965.00       -
228353          62,880                         965.00       -
228354          54,400                         245.54       -
228355          66,400                         243.63       -

Columns:
['Date', 'Symbol', 'Security Name', 'Client Name', 'Buy / Sell', 'Quantity Traded', 'Trade Price / Wght. Avg. Price', 'Remarks']

## **BSE Block Historical**

In [2]:
import pandas as pd
import glob
import os


folder_path = "/lakehouse/default/Files/data/raw/bse_block_hist"

files = glob.glob(
    os.path.join(folder_path, "*.csv")
)

print("Files found:", len(files))

all_data = []

for file in files:

    print("Reading:", os.path.basename(file))

    try:
        df = pd.read_csv(
            file,
            on_bad_lines="skip",
            low_memory=False
        )

        df.columns = df.columns.str.strip()

        print("Rows:", len(df))

        all_data.append(df)

    except Exception as e:
        print(f"ERROR -> {e}")


# Combine all files
df_final = pd.concat(
    all_data,
    ignore_index=True
)

# Remove duplicates
df_final = df_final.drop_duplicates()

# Convert Deal Date
df_final["Deal Date"] = pd.to_datetime(
    df_final["Deal Date"],
    dayfirst=True,
    errors="coerce"
)

# Sort by date
df_final = df_final.sort_values(
    "Deal Date"
)

# Convert back to readable format
df_final["Deal Date"] = (
    df_final["Deal Date"]
    .dt.strftime("%d-%m-%Y")
)

print("Final rows:", len(df_final))

file_path = os.path.join(
    folder_path,
    "blockdeals_01-06-2026.csv"
)

df_final.to_csv(
    file_path,
    index=False
)

print("Saved:", file_path)

Files found: 4
Reading: bse_block_2005_2010.csv
Rows: 2204
Reading: bse_block_2011_2015.csv
Rows: 3242
Reading: bse_block_2016_2020.csv
Rows: 4685
Reading: bse_block_2021_2026_may.csv
Rows: 11661
Final rows: 21240
Saved: /lakehouse/default/Files/data/raw/bse_block_hist/blockdeals_01-06-2026.csv

## **BSE Bulk Historical**

In [3]:
import pandas as pd
import glob
import os


folder_path = "/lakehouse/default/Files/data/raw/bse_bulk_hist"

files = glob.glob(
    os.path.join(folder_path, "*.csv")
)

print("Files found:", len(files))

all_data = []

for file in files:

    print("Reading:", os.path.basename(file))

    try:
        df = pd.read_csv(
            file,
            on_bad_lines="skip",
            low_memory=False
        )

        df.columns = df.columns.str.strip()

        print("Rows:", len(df))

        all_data.append(df)

    except Exception as e:
        print(f"ERROR -> {e}")


# Combine all files
df_final = pd.concat(
    all_data,
    ignore_index=True
)

# Remove duplicates
df_final = df_final.drop_duplicates()

# Convert Deal Date
df_final["Deal Date"] = pd.to_datetime(
    df_final["Deal Date"],
    dayfirst=True,
    errors="coerce"
)

# Sort by date
df_final = df_final.sort_values(
    "Deal Date"
)

# Convert back to readable format
df_final["Deal Date"] = (
    df_final["Deal Date"]
    .dt.strftime("%d-%m-%Y")
)

print("Final rows:", len(df_final))

file_path = os.path.join(
    folder_path,
    "bulkdeals_01-06-2026.csv"
)

df_final.to_csv(
    file_path,
    index=False
)

print("Saved:", file_path)

Files found: 9
Reading: bse_bulk_2001_2005.csv
Rows: 28436
Reading: bse_bulk_2006_2008.csv
Rows: 58013
Reading: bse_bulk_2009_2010.csv
Rows: 52302
Reading: bse_bulk_2011_2012.csv
Rows: 35393
Reading: bse_bulk_2013_2014.csv
Rows: 21502
Reading: bse_bulk_2015_2016.csv
Rows: 22542
Reading: bse_bulk_2017_2020.csv
Rows: 39440
Reading: bse_bulk_2021_2023.csv
ERROR -> 'utf-8' codec can't decode byte 0x96 in position 211405: invalid start byte
Reading: bse_bulk_2024_2026_may.csv
Rows: 49251
Final rows: 306789
Saved: /lakehouse/default/Files/data/raw/bse_bulk_hist/bulkdeals_01-06-2026.csv

In [4]:
import pandas as pd

file_path = "/lakehouse/default/Files/data/raw/bse_bulk_hist/bse_bulk_2021_2023.csv"

df = pd.read_csv(
    file_path,
    encoding="latin1",
    on_bad_lines="skip",
    low_memory=False
)

df.columns = df.columns.str.strip()

print(df.head())
print("Rows:", len(df))

    Deal Date  Security Code   Company                           Client Name  \
0  01/01/2021         539526      SCTL             MAYUR RAJENDRABHAI PARIKH
1  01/01/2021         526227   FILATEX        MODERN HI-RISE PRIVATE LIMITED
2  01/01/2021         534060    PMCFIN                     RAJESH  DHASAYYAN
3  01/01/2021         505523  MAHACORP  COBIA DISTRIBUTORS PRIVATE LIMITED .
4  01/01/2021         504335     PAZEL                AMIT HASMUKHBHAI PATEL

  Deal Type  Quantity  Price
0         S   4200000   0.81
1         S   3050000  46.03
2         S   2749999   0.45
3         S   1275000   0.67
4         S   1141090   0.21
Rows: 49958

In [5]:
import pandas as pd

# Existing final file
df_main = pd.read_csv(
    "/lakehouse/default/Files/data/raw/bse_bulk_hist/bulkdeals_01-06-2026.csv"
)

# Missing file
df_patch = pd.read_csv(
    "/lakehouse/default/Files/data/raw/bse_bulk_hist/bse_bulk_2021_2023.csv",
    encoding="latin1",
    on_bad_lines="skip",
    low_memory=False
)

df_main.columns = df_main.columns.str.strip()
df_patch.columns = df_patch.columns.str.strip()

# Combine
df_final = pd.concat(
    [df_main, df_patch],
    ignore_index=True
)

# Remove duplicates
df_final = df_final.drop_duplicates()

# Convert date
df_final["Deal Date"] = pd.to_datetime(
    df_final["Deal Date"],
    dayfirst=True,
    errors="coerce"
)

# Sort
df_final = df_final.sort_values(
    "Deal Date"
)

# Convert back to readable format
df_final["Deal Date"] = (
    df_final["Deal Date"]
    .dt.strftime("%d-%m-%Y")
)

print("Final rows:", len(df_final))

# Save final corrected file
df_final.to_csv(
    "/lakehouse/default/Files/data/raw/bse_bulk_hist/bulkdeals_01-06-2026.csv",
    index=False
)

print("Patched final file saved")

Final rows: 356696
Patched final file saved